### ISSUE TITLE
Random dates showing when datepicker opened using Google Chrome

### ISSUE THREAD

**Issue by YappyDog** [benitolopez/hotel-datepicker#100]
When I use a bare bones hotel-datepicker setup, and open using Chrome, I see a black bar with two dates in it (2021-03-15 to 2021-03-20).  This is shown on top of the two month calendars, and then never again until I refresh web page. It is always these same two dates.

Attached txt file shows the html I am using. Attached .png file shows what I am seeing. Works as expected on Edge & Firefox.

[index.html.txt](https://github.com/benitolopez/hotel-datepicker/files/6223435/index.html.txt)

![sample](https://user-images.githubusercontent.com/81582500/112874881-51560800-9078-11eb-9b0a-ceb88d932513.png)

**Comment by benitolopez** [comment]
I don't think this is something related to the library, the library doesn't create that popup.

Do you have the same problem with an incognito window (all extensions disabled) when you visit the demo?
http://lopezb.com/hoteldatepicker

**Comment by thekendog** [comment]
You need to set autocomplete="off" on the input element you are attaching the datepicker to.

**Comment by benitolopez** [comment]
Ha ok, now I understand. That's the autocompletion feature of Chrome. Yes, set it to off. The CSS provided by the library is just an example.
