### ISSUE TITLE
There is a way to show only one calendar in desktop?

### ISSUE THREAD

**Issue by fastrer** [benitolopez/hotel-datepicker#102]
There is a way to show only one calendar in desktop?

**Comment by benitolopez** [comment]
Hello, via CSS.

Check the example CSS included. The second month is hidden in mobile devices and visible after 480px:
https://github.com/benitolopez/hotel-datepicker/blob/master/src/sass/_base.scss#L58

Just hide the second month via CSS and you will have a single month.

**Comment by fastrer** [comment]
i tryed CSS  but this happens in desktop

![imagen](https://user-images.githubusercontent.com/16024712/127746594-3a45faba-5009-4245-ba30-81909ad88686.png)

**Comment by benitolopez** [comment]
Of course you need to adjust the css. The included css is just an example. Unfortunately I can’t help you.

**Comment by GeoffreyOlivier** [comment]
@fastrer Helle, have you find how to resize the calandar ? I have the same problem. Thanks
