### ISSUE TITLE
Sending Start and End Values to Hidden Fields.

### ISSUE THREAD

**Issue by tyekynan** [benitolopez/hotel-datepicker#104]
I am fairly new to coding, and I am having a very hard time sending the selected Check-In and Check-out dates to two seperate hidden inputs (one for checkin and one for checkout). Does anyone have advice? Any help is appreciated.

I have tried using d1 and d2, but that doesn't seem to work. An example would be fantastic, as long as it shows how to grab the selected checkin date and then grab the selected checkout date. Sorry if this seems ridiculous of me to ask, just trying to learn and move forward.

**Comment by benitolopez** [comment]
Hello,

Unfortunately this place is to reporting bugs, you can use stackoverflow to ask questions about code. 

You can check this file: 
https://github.com/wp-hotelier/wp-hotelier/blob/master/assets/js/frontend/hotelier-init-datepicker.js#L82

In that example, after the selection the values are sent to two hidden input fields. You can try to follow that code, it's basically what you're asking for.
