### ISSUE TITLE
Using destroy more than once throws a console log error.

### ISSUE THREAD

**Issue by tyekynan** [benitolopez/hotel-datepicker#105]
When I use destroy(). It works the first time. If I reopen the modal window and create a new datepicker, when I click on close again, it does destroy the datepicker as it should, but it throws this error in the console log: 

Uncaught TypeError: Cannot read properties of null (reading 'removeChild')

This only happens if I destroy the same datepicker more than once. Does not happen the first time. But it does seem to remove the DOM elements every time as it should.

```
let getDatePickers = function(response) {

  var lockedDates = [];
  for(var i = 0, len = response.length; i < len; i++){ 
    let lockDate = response[i].staydate;
    lockedDates.push(lockDate);
  }

  var today = new Date().getHours();
  if (today >= 0 && today < 7) {
    var maxDay = moment().add(340, 'days').format('MM-DD-YYYY');
  }
  else {
    var maxDay = moment().add(341, 'days').format('MM-DD-YYYY');
  }

  let datepicker = new HotelDatepicker(document.getElementById(response[0].room + '-datepicker'), {
    format: 'MM-DD-YYYY',
    infoFormat: 'MM-DD-YYYY',
    minNights: 1,
    maxNights: 29,
    disabledDates: lockedDates,
    noCheckInDates: lockedDates,
    startDate: moment().add(1, 'days').format('MM-DD-YYYY'),
    endDate: maxDay,
    enableCheckout: true,
    autoClose: false,
    preventContainerClose: true,
    moveBothMonths: true,
    selectForward: true,
    setValue: function (s, s1, s2) {
      var checkin = new Date(s1);
      var checkout = new Date(s2);
      var checkin_formatted = fecha.format(checkin, 'YYYY-MM-DD');
      var checkout_formatted = fecha.format(checkout, 'YYYY-MM-DD');

      document.getElementById(response[0].room + '-partialcheckin').value = checkin_formatted;
      document.getElementById(response[0].room + '-partialcheckout').value = checkout_formatted;
    },
    onSelectRange: function(getPrice) {

      let checkin_date = document.getElementById(response[0].room + '-partialcheckin').value;
      let checkout_date = document.getElementById(response[0].room + '-partialcheckout').value;
      let roomcode = response[0].room;

      j$.ajax({
        url: "../components/com_checkavail/controller/partial-avail-calc.php",
        type: "POST",
        data: { roomcode: roomcode, checkin_date: checkin_date, checkout_date: checkout_date},
        dataType: "json",
        success: function (response) {
          let container = document.getElementById(response[0].room + '-partialdatePrice')
          let cost = (response[0].price)*1.04;
          let frmtcost1 = Math.round(cost);
          let frmtcost2 = frmtcost1.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

          container.innerHTML = 'Total Price: $' + frmtcost2;
        }
      })
    }
  })

  var destroyButton = document.getElementById(response[0].room + '-closebtn');
  destroyButton.addEventListener('click', destroyDatepicker);

  function destroyDatepicker() {
    datepicker.destroy();
  }
}
```

**Comment by benitolopez** [comment]
Hello,

I don't know why you're destroying the datepicker but after destroying it, to destroy it again you need to re-instantiate a new datepicker. 

Check the demo here:
https://github.com/benitolopez/hotel-datepicker/blob/master/demo/index.html#L593

As you can see, before to destroy it, I check if the datepicker exists.

**Comment by tyekynan** [comment]
I have about 140 buttons on a page. Each button opens a different modal window. Each modal window makes an ajax request to get disabled dates.

If I do not destroy it, the datepicker acts weird, as in... I can select a checkin and check out... and then it wants to allow me to select a future date keeping the original selected checkin date.

When I use destroy it seems to fix that. If I close the modal window once, it seems to work fine. When I reopen the model, it pulls in my new datepicker and it works great, but I receive that error when I close it again. 

This function is currently tied to the button that opens the modal window. The demo link you sent is what I went by. I have been wrong before but it is coded to re-instantiate a new picker each time the button is clicked to open the modal window.

Note the button click on this class pushes the getDatePickers function that I initially posted.

```
let createAvailCheck = function(response){
  let availchecks = document.querySelectorAll('[id$="-availcheck"]');
  availchecks.forEach(function(availcheck){
  j$(availcheck).click(function () {
    var roomcode = availcheck.dataset.roomcode;
    j$.ajax({
      url: "../components/com_checkavail/controller/partial-avail-check.php",
      type: "POST",
      data: { roomcode: roomcode},
      dataType: "json",
      success: function (response) {
          getDatePickers(response);
      }
      })
  })
})
}
```

**Comment by tyekynan** [comment]
Maybe my explanation isn't super clear... here are some photos to help me explain.

All of the see availability buttons trigger a modal window. They also trigger my "new HotelDatepicker". If I click on the first "See Availability" button.... we move on to the second screenshot.
![1](https://user-images.githubusercontent.com/78494359/133894764-0d40b330-35f5-491f-a404-12301c666260.PNG)



Here you can see that everything opens and it creates my datepicker. It works great and I have found no issues. If I select the close button, it destroys my datepicker and closes the modal window. We move on to screenshot 3.
![2](https://user-images.githubusercontent.com/78494359/133894828-74f8425d-e25b-492b-b60f-95bb0f0f91bf.PNG)



We are now back on the main page. If I select the first "See Availability" button again.... We move on to screenshot 4.
![1](https://user-images.githubusercontent.com/78494359/133894865-06d4c027-ee72-42a7-bf94-346e0e172662.PNG)



Everything looks normal again, and even though not shown in my screenshot, the console elements section shows a new div was created for the datepicker. However, when I click the close button... we move on to screenshot 5.
![2](https://user-images.githubusercontent.com/78494359/133894880-53370036-a14e-41d1-84f2-ba62c02aa1a1.PNG)



Now I have a console log error. If I check the elements tab, it does show that it destroyed the datepicker and I can repeat the process and it will open a new one like it is supposed to.  This only happens if I have already clicked the "Close" button for that specific room once. It never happens the first time, and it always creates a new datepicker.
![3](https://user-images.githubusercontent.com/78494359/133894904-703bdfbd-ff78-4e39-9a94-886faad3dcf9.PNG)



It seems to work accordingly, but the error seems odd, and I wasn't sure if it was a bug that needed to be reported? Or if someone on my end was causing it and it could cause issues down the road.

**Comment by tyekynan** [comment]
If I use the if statement provided in the demo to show if it exists before destroying it. It still works as intended but shows the same console log error when destroying more than once. I am just not changing the text of the button.

```
  var destroyButton = document.getElementById(response[0].room + '-closebtn');
  destroyButton.addEventListener('click', destroyDatepicker);

  function destroyDatepicker() {
    if (document.getElementById(response[0].room + '-datepicker')) {
    datepicker.destroy();
    }
    else {

    }
```

**Comment by benitolopez** [comment]
If you have that error it means that the datepicker you're trying to destroy doesn't exist. Probably this is true because you have an element with that ID but it is not a datepicker:
`if (document.getElementById(response[0].room + '-datepicker')) {`

Try to check the value of the datepicker variable when you have the error:

```
function destroyDatepicker() {
    if (document.getElementById(response[0].room + '-datepicker')) {
        console.log(datepicker);
        datepicker.destroy();
    } else {

    }
```

Probably it will be undefined or something like that. Then you will be able to use that value in your check before to destroy it.

**Comment by tyekynan** [comment]
I'll check that but... this is where I am confused... the datepicker works... it creates it, destroys it, and re-creates it everytime. I am just not sure if the error is a problem...

Here are screenshots of the elements.

I click "see availability"... datepicker appears in elements
![1](https://user-images.githubusercontent.com/78494359/133896097-ba6a8061-eacb-43c4-9204-43c5ec750f9b.PNG)



I click "close".... datepicker is removed from elements
![2](https://user-images.githubusercontent.com/78494359/133896104-4d3dd235-13c9-4f52-b8c2-4507d817ccb5.PNG)



I click "see availability" again... it is recreated in elements.
![3](https://user-images.githubusercontent.com/78494359/133896117-0124710d-600a-4502-b2cf-9f47bfc2de48.PNG)


I can do this over and over again and functionality seems fine? I haven't noticed issues, but the error is throwing me off.

**Comment by tyekynan** [comment]
So when I click "close" the first time. It seems it works correctly...
![dp1](https://user-images.githubusercontent.com/78494359/133896229-511d8c7a-67ab-4e41-91ae-e94907aae617.PNG)


When I click "close" the second time, console logs the datepicker... throws an error.... and then console logs the datepicker a 2nd time. 
![dp2](https://user-images.githubusercontent.com/78494359/133896251-52ae34ba-4573-49e3-880e-44002acf2e67.PNG)
.

**Comment by benitolopez** [comment]
Honestly I don't know. Unfortunately you have a complex setup and it is not easy to debug from a couple of screenshots. I think that the problem is related toevents binded to elements that don't exist anymore. 

In your case, sometimes the parent node is null:
https://github.com/benitolopez/hotel-datepicker/blob/master/dist/js/hotel-datepicker.js#L1661

I can't know the reason from here. This is something you need to debug yourself.

**Comment by tyekynan** [comment]
I'll look into it. I didn't realize there was a demo I could run and see if the problem persisted myself. I appreciate the feedback and quick responses. Your datepicker is lovely.

**Comment by tyekynan** [comment]
Future Reference: If I use the jquery remove() method instead of destroy() and then target the "datepicker-**-datepicker" element. The error goes away and everything seems to run fine. It ran fine anyway, and I doubt the error was creating issues, but they get on my nerves having to look at them.
