### ISSUE TITLE
endDate seems not working

### ISSUE THREAD

**Issue by coeuryv** [benitolopez/hotel-datepicker#106]
Trying to use endDate to avoid uses too far in the future, but it doesn't work: i can select dates after the one i set. 
Here's a part of the code i use. 
noCheckInDates works well, as do the other options sets before disabledDates. 

        disabledDates:[
        ],
        endDate: '2022-01-31',
        noCheckInDates: [

            '2021-10-15',
]

**Comment by benitolopez** [comment]
I can't reproduce the issue, working fine on my end. Can you share a URL?

**Comment by coeuryv** [comment]
Hello there,

You can see it at this url :
https://www.kot.chat/index.php

I join a screenshot of the code here.

I can't let it online as is more then 3 days

Bien à vous,

[image: image.png]

Le mer. 3 nov. 2021 à 10:21, Benito Lopez ***@***.***> a
écrit :

**Comment by benitolopez** [comment]
The `endDate` must be a date object or a string in the same format you're using for the datepicker. In your case `'DD-MM-YYYY'`. I need to add a note in the readme because it can be confusing considering that the other options are in the `'YYYY-MM-DD'` format. Unfortunately, I can't change that option to the `'YYYY-MM-DD'` format as well because this will break a lot of installations.

**Comment by coeuryv** [comment]
Hi there,

Thank you for you quick answer. Now, it works perfectly.
A read me note would be a great thing.

The confiusing thing is that i use : format: 'DD-MM-YYYY',
but for noCheckInDates and noCheckOutDates you still have to use
'YYYY-MM-DD'.
If i use the format 'DD-MM-YYYY' it doesn't work for them.

The bug might be there ?
I join a screen shot of what i mean.


[image: image.png]




Le mer. 3 nov. 2021 à 23:43, Benito Lopez ***@***.***> a
écrit :

**Comment by benitolopez** [comment]
That's exactly what I said above. noCheckInDates and noCheckOutDates use the 'YYYY-MM-DD' format (it is mandatory and cannot be changed, it is not a bug). But endDate not. The problem is that I can't change this without breaking existing installations. So the only solution is to add a note.

**Comment by coeuryv** [comment]
Ok, sorry, my english is quite poor and i didn't understand clearly what
you first said.
Anyway, it works well now, thank you a lot for your whole work.


Le jeu. 4 nov. 2021 à 07:50, Benito Lopez ***@***.***> a
écrit :
