### ISSUE TITLE
Is it possible to select 1 date instead of a range

### ISSUE THREAD

**Issue by jcsdesterke** [benitolopez/hotel-datepicker#108]
Hello there,

I want the picker to select 1 date instead of a complete range.
The design I am developing uses seperate input fields for the start and end date so I would like to select an individual date in each input field.

How can I achieve this?

Thanks!

**Comment by benitolopez** [comment]
Hello, 

This is not possible. This is a specific date _range_ picker and doesn't have that functionality intentionally.
