### ISSUE TITLE
Inline calendar

### ISSUE THREAD

**Issue by lupus78** [benitolopez/hotel-datepicker#109]
Great stuff, thanks for your work. 

Have you considered adding "inline": true/false option? Instead of dropdown calendar, the calendar would be always visible. I know I can user open() function and add position:relative to the .datepicker div for a quick solution, but a proper configuration attribute would be cleaner.

**Comment by benitolopez** [comment]
Hello,

I've been asked this a couple of times before and find it interesting. If I have some time to implement it I will gladly do so. But right now it's not a priority. I will look into it though.

**Comment by benitolopez** [comment]
Added support for inline mode in last release (4.1.0).
