### ISSUE TITLE
Destroy calendar, or refresh

### ISSUE THREAD

**Issue by speedwheel** [benitolopez/hotel-datepicker#11]
Hello, I want to update the calendar's disabledDates after it was  #initalised, I am thinking that the most easy way would be to destroy the calendar and initiate it again, how can I do that?

If I do this it's good?

```js
$('#datepicker-clientCalendar').remove();
```

And then reinitialise it with the new options.

**Comment by benitolopez** [comment]
The public methods available are visibile in the plugin's description. There's not a destroy method. I will check in the next weeks how much murk is required to add such method but I can't assure anything. The purpose of this plugin is to maintain the code and the features simple as much as possible.

**Comment by speedwheel** [comment]
@benitolopez Thanks, it shouldn't be complicated, for me it works fine with the code I posted above, but I am not sure if this is the best approach.

**Comment by voldermord** [comment]
Hello, I am also looking for a way to reload the disabled dates, cant find any method to do so or destroy current instance. Re-initializing the code breaks the control.

**Comment by speedwheel** [comment]
@voldermord For me it works fine if I use:

```js
$('#datepicker-clientCalendar').remove();
```

**Comment by benitolopez** [comment]
Added `destroy()` method. Check the demo.

**Comment by speedwheel** [comment]
@benitolopez Thanks!
