### ISSUE TITLE
minNights should be on a day-level

### ISSUE THREAD

**Issue by parijke** [benitolopez/hotel-datepicker#111]
First of all, what a nice job! I have a question or suggestion though.

Suppose you build a calendar for a hotel, and for some reason (example holiday-season) in certain periods the minNights should be 7, while on other periods is could be 3 (or whatever).

I cannot see how to do this at the moment? You can (as far as I can see in the documents) only set the minNights for the whole calendar.

**Comment by benitolopez** [comment]
Hello,

Yes it's correct, there's not the possibility to set seasonal min/max nights. I would love to introduce this feature someday but I don't have the time right now.
