### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by ikabod** [benitolopez/hotel-datepicker#112]
Hello,

thanks for this nice date range picker.

But the behavior of the picker is not, what a user would expect.

Currently the user can pick a start and an end date in the left, the right or both sides of the picker. This causes that he can not correct a wrong date without starting from scratch.

Example: User opens the date picker an clicks on the first Mai on the left side and on the first June on the right side. If he reopens the picker, and wants to correct the end date to the 2nd June, he must first click again on the first Mai and then on the 2nd June.

He can also not correct a wrong start date. If he clicked on the 2nd Mai instead of the first Mai, he is forced to first select an end date, before he can correct the start date. This is also more annoying, if autoclose is enabled.

Why not select the start date (regardless when) only on the left side and the end date only on the right side? This would drop the hover ability I guess, but this is only a nice optical feature which is not more important than user experience.

In this way you could easily correct start and/or end dates and would make the picker much more better.

**Comment by benitolopez** [comment]
The direction of the selection can be set from left to right setting the `selectForward` option to true: https://github.com/benitolopez/hotel-datepicker#selectforward

But yes, this is a daterange picker so every time you click on a date the range resets and you need to re-start again. It can be annoying, I admit. But no one has complained about it over the years so right now it is not my priority to change the behaviour of this thing. It is not that simple to solve.
