### ISSUE TITLE
Feature Question: Re-initialise existing Datepicker with new disabledDates

### ISSUE THREAD

**Issue by meneer-code** [benitolopez/hotel-datepicker#113]
Hi there

Just a quick question to check if something is possible since I can't find it in the docs:

In some cases my availability is outdated, then I receive a response with new disabledDates. Is it possible to take this json and re-initialise the same datepicker with the new dates without having to reload the page to re-initialise the datepicker?

**Comment by benitolopez** [comment]
Hello,

There's not an update method. You need to re-initialise the datepicker or make the AJAX call before to initialise it.
