### ISSUE TITLE
startDate and endDate not working like stated in guide and startDate improvements (if set in past)

### ISSUE THREAD

**Issue by stefano-frigerio** [benitolopez/hotel-datepicker#118]
startDate and endDate are required to be string type otherwise startDate.getTime(), so you should add in the guide apexes, which also seems to not work.
If you set startDate, you should check if it is in the past or in the future and update selection of startDate based on this, like:

row 20: this.startDate = new Date(opts.startDate).getTime() > new Date().getTime() ? new Date(opts.startDate) : new Date();
row 21: this.endDate = new Date(opts.endDate) || false;

**Comment by benitolopez** [comment]
Hello,

Regarding the startDate/endDate type, dates work. You can check it in the demo (the datepicker with ID "demo8" for example):
http://lopezb.com/hoteldatepicker/

Can you explain better the other problem (rows 20/21)?

**Comment by stefano-frigerio** [comment]
When you set startDate you aren't checking if startDate is in the past, so users can select a date in the past for check in. I know it doesn't make sense, it's just to prevent a distracted user from selecting dates before today as check in. (you can simply try putting 2022-07-05 and clicking any date between 2022-07-05 and today)

**Comment by benitolopez** [comment]
Ok, now I understand. With `startDate` you can set a date in the past, this is intentionally. And some users are already using it in that way. For example: https://github.com/benitolopez/hotel-datepicker/issues/88

Please note that `startDate` and `endDate` are not the checkin and checkout. Is the start and the end of the calendar where the user can select a checkin/checkout.  

In doc https://github.com/benitolopez/hotel-datepicker#startdate): 
_The **start view** date. All the dates before this date will be disabled._

So, that just leaves the question of the type of `startDate` and `endDate`. You say it doesn't work with date types. Can you please check the demo to see how it works and, if the issue persists, possibly upload an example somewhere?
