### ISSUE TITLE
How can we disable typing?

### ISSUE THREAD

**Issue by sarathiscookie** [benitolopez/hotel-datepicker#12]
Hi, this is really a good one for booking system. How can we disable typing. Is there any built in function?

**Comment by benitolopez** [comment]
Hi,

Sorry but I didn't understand. What do you mean for "disable typing"? To select a date range you need to "click".

Anyway, the available methods are described in the readme.

**Comment by sarathiscookie** [comment]
At-present I can type some text in daterange text box. When I submit form the posted result looks likes 
eg: 10.11.1dgdgdg7 - 23.11gdgdf.dgdggdfgdfgdgd17. I hope now you got the point.

**Comment by benitolopez** [comment]
Now I understand what you mean. Well, you should validate the sent form data in any case, the datepicker doesn't validate the data for you.

Anyway, to prevent typing you can use a simple trick: just add the attribute `readonly` to your input.

```
<input type="text" id="your-id" value="" readonly="readonly">
```
