### ISSUE TITLE
Text issue when you set min & max nights to same number

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#122]
When setting the `minNights `& `maxNights `to the same number, the next text is a bit weird:
`'info-range': 'Please select a date range between %d and %d nights',`

For me I could do a workaround and overwrite the text with the `i18n` option because for me the min and max nights will always be the same number.

**Comment by benitolopez** [comment]
I agree. Next release will have a new string. You can already check it: https://github.com/benitolopez/hotel-datepicker/commit/85b3dc5ad48f8d18037808cdb28f17f29e51f5cd

**Comment by JordyGit** [comment]
Hi, I checked the commit and you will need to add the original text in the else block or it will overwrite your change i think. :)

**Comment by benitolopez** [comment]
You are right. This is what happens when you work in the evening :) Fixed in 4.3.2
