### ISSUE TITLE
4.3.1 Reset button doesn't properly reset the form in the edge case from #120

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#123]
1.36.1 Reset button doesn't properly reset the form in the edge case from #120 , same code

Gif:
![Animatie2](https://user-images.githubusercontent.com/33500507/182475271-91e86794-8e58-4ee0-b589-29dccb47a4bd.gif)

**Comment by benitolopez** [comment]
Yep. https://github.com/benitolopez/hotel-datepicker/commit/0d6cb17734cefc802dad777946d00961450dcad3 should fix the issue.
