### ISSUE TITLE
Too long translations will overflow behind buttons

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#125]
I am translating and also adding extra feedback for the user via the translation i18n translation option. When my text gets too long it will get hidden behind the buttons etc. I tried some guesses to fix it nicely with CSS but didn't find a good workaround yet.

![trans](https://user-images.githubusercontent.com/33500507/182666976-58c21336-7fa1-42cc-a88f-39ed40066f8e.png)

**Comment by benitolopez** [comment]
Hi, you can try something like:

```
.datepicker__info--help {
	max-width: 60%;
}
```

Anyway, please note that the datepicker style is only a starting point. It is not intended as a final solution. It was made as an example so everyone must make the necessary adjustments.

**Comment by JordyGit** [comment]
I understand, of course.

The max width will work, but then if the page is resized smaller, the buttons appear below and text would be too small. Would probably also need a `@media screen and (max-width: XXXpx)` on that CSS. I'll check it out and update this post or make a PR :)

**Comment by JordyGit** [comment]
See #129
