### ISSUE TITLE
Question: Is it possible to edit a property set with the constructor?

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#126]
Is it possible to edit a property set with the constructor? 

I tried the following but this has no effect: 
```
var rangePicker = new HotelDatepicker(document.getElementById('range-input-parent'), {inline: true});
rangePicker.minNights = 6;
rangePicker.maxNights = 6;
```

So what I'm gonna do instead is destroying the rangePicker and create a new one each time I need to make an adjustment. To me it just feels not as efficient as being able to edit the property, but that could be me?

**Comment by benitolopez** [comment]
Hi,

It is not possibile. You need to destroy and re-initialize it again.
