### ISSUE TITLE
Issue with disabled checkouts/checkins in reverse order

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#127]
I was playing a bit with the demo page and found out when you do the reverse range select (first select the check out day, then the check in day) the disabled checkouts/checkins are not applied correctly.

**Comment by benitolopez** [comment]
Fixed in 4.3.3

**Comment by JordyGit** [comment]
Hi, It is indeed fixed in the normal order cases, but not in reverse order (block all while it should allow some cases). I created and documented the bug in #133
