### ISSUE TITLE
Issue: display:none; on the outer div of the picker will make the month icons shown incorrectly

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#128]
Issue: `display:none;` on the outer div of the picker will make the month icons shown incorrectly when you make the outer div `initial`, `unset` etc to make it visible after some other user input for example

Workaround:
use `visibility: hidden;` instead on the outer div, but the downside is this is still taking up the size on the page

Gif:
![weird months arrows](https://user-images.githubusercontent.com/33500507/183156931-99f8b587-3490-43f1-a7ed-e3b812fd63fb.gif)

code:
```
<div class="col-sm-12 text-center mt-30" id="range-content" style="display: none;">
		<div class="demo__input" id="range-input-parent">Laden...</div>
</div>
```

**Comment by JordyGit** [comment]
Made this is not really an issue but me using the display styling wrong? But it's nice to have it documented (if it doesn't has to be fixed) so if anybody else would have the issue they can easily find out why and how to fix it.

**Comment by JordyGit** [comment]
Also if the display style is put to none/initial after the first (buggy) time it's all going fine. So maybe it's like a first time load issue?

**Comment by benitolopez** [comment]
This is an issue related to your CSS code. Probably after changing the display type of the outer div you should fix the display of those buttons as well.

**Comment by JordyGit** [comment]
Yes, but I thought maybe it could be an initialization issue which would avoid this.
