### ISSUE TITLE
disabledDaysOfWeek are not disabled to be part of a range

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#132]
disabledDaysOfWeek are not disabled to be part of a range, which they should?

See Gif:
![gif](https://user-images.githubusercontent.com/33500507/183247133-d695c4df-1e1b-4db7-a007-a059dde69152.gif)

**Comment by benitolopez** [comment]
Fixed in 4.3.3

**Comment by JordyGit** [comment]
Indeed, validated and seems being fixed correctly 👍
