### ISSUE TITLE
Feature request: no Check In/Out days of week

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#134]
At this moment we can have both disabled **days** (`disabledDaysOfWeek`) & disabled **dates** (`disabledDates`), compared to only being able to set `noCheckInDates`/`noCheckOutDates `and no `noCheckInDaysOfWeek`/`noCheckOutDaysOfWeek`.

This results in the need to loop over all days shown in the calendar and add them to the list of noCheckInDates/noCheckOutDates if needed, while it could be way more performant using this suggested feature. 

This could be used to:
- only support booking a single fixed range (_eg Monday to Friday_)
- depending of business days mark them as noCheckInDayOfWeek/noCheckOutDayOfWeek (_eg never checkout or checkin on Thuesday_)

**Comment by benitolopez** [comment]
Added in 4.4.0

**Comment by JordyGit** [comment]
Thanks! This will be a life saver for me. I'll check it out right away and use it in my code instead of looping over all those days.
