### ISSUE TITLE
Month icons not initialized correctly after switching from landscape to portait for the first time

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#136]
The icons of the months are not initialized correctly on mobile when you go from portrait to landscape for the first time. (When it goes from single month to 2 month display)
After switching months one time it corrects itself and the issue is gone.

I'm using the `moveBothMonths: true` option.

(Iphone 12 pro max, ios 14.5.1)
See:

https://user-images.githubusercontent.com/33500507/184018334-acac9799-1155-4ac4-b0ad-e13ec7bfba71.mov

**Comment by JordyGit** [comment]
Also if you are at the last month an go from landscape to portait it resets to the first month.
In landscape the next or prev button is gone when you reach the end or start but it doesn't go away in portair, it's displayed but as expected it doesn't do anything anymore in that case.

**Comment by benitolopez** [comment]
Please check: https://github.com/benitolopez/hotel-datepicker/commit/87e618a57c68ba0a0ff14e13c8bc21edcf875faa

**Important**: after the resize, months are reset. So if you have a valid selection, it goes to the months with that selection. If there's not a selection, you go to the first month. 

So this:

> Also if you are at the last month an go from landscape to portait it resets to the first month.

It is not a bug, it is how it works.

**Comment by JordyGit** [comment]
Ok I understand but would expect it to go to the same month, that is why I thought it was a bug.
