### ISSUE TITLE
disabledDates issue since 4.4.0

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#141]
Disabled Days with `disabledDates` become selectable and behave weird, see gif.

Weird:
![disabledDaysBug](https://user-images.githubusercontent.com/33500507/184498833-374cef22-6781-46a7-b7f2-33c97d64bbf3.gif)

**Comment by JordyGit** [comment]
The same issue seems to happen with `disabledDaysOfWeek`.

**Comment by benitolopez** [comment]
Code?

**Comment by JordyGit** [comment]
It becomes harder to share code examples because it's loaded dynamically from my database now.

Just disable some dates or days and the issue like in the GIF happens.

var rangePicker = new HotelDatepicker(rangePickerElement, {
    inline: true,
    clearButton: true,
    topbarPosition: 'bottom',
    moveBothMonths: true,
    selectForward: false,
    startOfWeek: 'monday',
    format: 'DD/MM/YYYY',
    disabledDates: [
        "2022-08-09",
        "2022-08-10",
        "2022-08-11",
        "2022-08-12",
        "2022-08-13",
        "2022-08-14",
        "2022-08-16",
        "2022-08-17",
        "2022-08-18",
        "2022-08-19",
        "2022-08-20",
        "2022-08-21",
        "2022-08-23",
        "2022-08-24",
        "2022-08-25",
        "2022-08-26",
        "2022-08-27",
        "2022-08-28",
        "2022-08-30",
        "2022-08-31",
        "2022-09-01",
        "2022-09-02",
        "2022-09-03",
        "2022-09-04",
        "2022-09-06",
        "2022-09-07",
        "2022-09-08",
        "2022-09-09",
        "2022-09-10",
        "2022-09-11",
        "2022-09-13",
        "2022-09-14",
        "2022-09-15",
        "2022-09-16",
        "2022-09-17",
        "2022-09-18",
        "2022-09-20",
        "2022-09-21",
        "2022-09-22",
        "2022-09-23",
        "2022-09-24",
        "2022-09-25",
        "2022-09-27",
        "2022-09-28",
        "2022-09-29",
        "2022-09-30",
        "2022-10-01",
        "2022-10-02",
        "2022-10-04",
        "2022-10-05",
        "2022-10-06",
        "2022-10-07",
        "2022-10-08",
        "2022-10-09",
        "2022-10-11",
        "2022-10-12",
        "2022-10-13",
        "2022-10-14",
        "2022-10-15",
        "2022-10-16",
        "2022-10-18",
        "2022-10-19",
        "2022-10-20",
        "2022-10-21",
        "2022-10-22",
        "2022-10-23",
        "2022-10-25",
        "2022-10-26",
        "2022-10-27",
        "2022-10-28",
        "2022-10-29"]
);

**Comment by JordyGit** [comment]
Issue also happens with `noCheckInDaysOfWeek`, `noCheckOutDaysOfWeek`, `noCheckInDates`, `noCheckOutDates`

**Comment by JordyGit** [comment]
DaysOfWeek/Dates that are Disabled but **also** are NoCheckIn or NoCheckOut DaysOfWeek/Dates don't have the issue and are not selectable.

**Comment by benitolopez** [comment]
I'm not able to reproduce the issue with your example. And I don't see the issue in the demo as well:
http://lopezb.com/hoteldatepicker/

**Comment by JordyGit** [comment]
Hmmm, I will look more into it next time.

**Comment by JordyGit** [comment]
I tried it again with the same example and i still have that issue. I disabled my custom css this time so you can see what is happening easier:
![dfdfd](https://user-images.githubusercontent.com/33500507/184502123-9577d35c-90e8-4c4e-bd0e-a035d2586000.gif)

**Comment by benitolopez** [comment]
Trey now: https://github.com/benitolopez/hotel-datepicker/commit/1ff372d25214430727d0337a26adad8b389969e0

Bug was introduced by: https://github.com/benitolopez/hotel-datepicker/commit/781fb5747c255e4d09934adaf8f0beff444b0c0d

**Comment by JordyGit** [comment]
Hi, the issue is still not resolved with the JS file from master.
Same example:
![issue](https://user-images.githubusercontent.com/33500507/184657651-d961e1f5-a970-4c7e-bbda-6d4ca5d99ee0.gif)

**Comment by JordyGit** [comment]
Yes, the initial issue seems to be fixed now, but another thing started happening now: Monday 3th, 12th, 19th.. becomes selectable. Before it wasn't because there was no valid range possible to be selected (one day between disabled dates)

Same example with master js:
![issue2](https://user-images.githubusercontent.com/33500507/184673976-81f5768b-15e2-48d6-8a50-031893d56cc4.gif)

**Comment by benitolopez** [comment]
Yes, try now again

**Comment by JordyGit** [comment]
I've changed my answer a bit, i noticed this was already happening before.

I'll test master again... ;)

**Comment by JordyGit** [comment]
On the new master all of this is good now.
Only this started happening now, which was not the case before:
- When you select a valid range on the right calendar, the calandar goes to the next month so that month is shown on the left calendar

**Comment by benitolopez** [comment]
You're right, that's not good.

I rewrote some of the code and now everything should work. Please check

**Comment by benitolopez** [comment]
You're right, that's not good.

I rewrote some of the code and now everything should work. Please check

**Comment by JordyGit** [comment]
Hi!
Checked and all seems good, can't find any more bugs/issues :) nice work!
Thanks again for the fixes and new features, really appreciate it!
