### ISSUE TITLE
Feature request: select a range with one click if nothing else is possible

### ISSUE THREAD

**Issue by JordyGit** [benitolopez/hotel-datepicker#151]
If I define a range of a few days (eg 3) and disable some week days (eg mo-thur), my calendar would be in a state so it can only select weekends. 
Atm a user is required to click on the first AND the last day (fri & sun) (works in both orders).
UX could be improved so that the user could click any day of the range (fri, sat or sun) in one click to select the full range.

**Comment by benitolopez** [comment]
This is a great idea but not easy to implement. And unfortunately I don't have the time to develop it. Anyway, feel free to open a pull request if you want to work on it.
