### ISSUE TITLE
Flexible Month display

### ISSUE THREAD

**Issue by stell** [benitolopez/hotel-datepicker#152]
What would move things forward a lot would be the ability to flex the number of months in a grid layout.
I've played around with a fork a bit and it's not rocket science.

**Comment by benitolopez** [comment]
Hello,

Can you explain better and show an example?

**Comment by stell** [comment]
Hi,
being able to display one, two or more months when opening the picker.
Also displaying a grid of months inline, like 4x3 and similar.

**Comment by benitolopez** [comment]
Now I understand. No, this is something that it is not planned. Apparently it looks simple but it involves a lot of complication and difficulty in maintaining the code. I'm sorry but I am unable to introduce such a feature.
