### ISSUE TITLE
How to turn-off the one day notice for check-in on the same day as someone's else check-out?

### ISSUE THREAD

**Issue by 3nematix** [benitolopez/hotel-datepicker#154]
Let's say that someone has booked their apartment from `2023-01-19 to 2023-01-21` and someone wants to book their apartment from the day that the these people will check-out (2023-01-21).  As we can see in the photo below if the new check-out date would be 2021-01-23 (day before other people reservation) these people would be able to check-out, but is there any way to check-out on the same-day as other people has their check-in? For example their new check-in would be on the same day but let's say at around 3-7 PM so the people that had their check-out they would be already gone at around 11-12 AM or etc..

Is there any way to disable "One-day notice" or how is it called?:)

In this example I can only check-out at 2021-01-23, but can't at 24.
![image](https://user-images.githubusercontent.com/46891372/213340168-cd2f8924-c7c0-4815-a737-25049c53a657.png)

Thanks!

**Comment by 3nematix** [comment]
![image](https://user-images.githubusercontent.com/46891372/213340929-1dca797c-3efd-46e1-ae68-afde29418248.png)

**Comment by 3nematix** [comment]
When using `enableCheckout: true` this weird logic appears, it now let's to check-out on the first check-in date of others, but also allows the second day.

My suggestion is to use date format with time? So then people can provide their check-in date with time and then we can compare the both times if it would fit in the range of check-in out times

![image](https://user-images.githubusercontent.com/46891372/213341935-338b9a4a-8b8b-4476-bea1-17e68a0c997a.png)

https://i.gyazo.com/e9033419c615f91e39e088d9059ddf8e.mp4

**Comment by 3nematix** [comment]
```
            const booking_date_calendar = document.getElementById('dates');

            if (booking_date_calendar) {
                const disabled_dates = window.page_data.booking_dates.disabled_dates || [];
                const no_check_in_dates = window.page_data.booking_dates.no_check_in_dates || [];
                const no_check_out_dates = window.page_data.booking_dates.no_check_out_dates || [];

                var datepicker = new window.hotelDatepicker(booking_date_calendar, {
                    minNights: 1,
                    clearButton: true,
                    autoClose: false,
                    enableCheckout: true,
                    selectForward: true,
                    preventContainerClose: true,
                    disabledDates: disabled_dates,
                    noCheckInDates: no_check_in_dates,
                    noCheckOutDates: no_check_out_dates,
                });
            }

```
![image](https://user-images.githubusercontent.com/46891372/213342404-70bebaf4-ad74-4efa-abe8-89faa749984e.png)

**Comment by 3nematix** [comment]
if we would change `datepicker__month-day--invalid -> datepicker__month-day--valid` we would be able to check-out at that day

```
<td daytype="visibleMonth" time="1674511200000" d="3" role="button" index="24" aria-label="Not available, Tuesday, January 24, 2023" aria-disabled="true" class="datepicker__month-day datepicker__month-day--visibleMonth datepicker__month-day--invalid      datepicker__month-day--no-checkin ">24</td>
```

**Comment by 3nematix** [comment]
Very strange, in this screenshot I can book from 19-20 day but 23-24 is not possible (20, 24 days ar check-in dates)

![image](https://user-images.githubusercontent.com/46891372/213353059-d64440f1-47a2-4e92-b950-f6178066771e.png)

**Comment by benitolopez** [comment]
Ok, it seems the issue is that disabled dates are selectable if they come after a `noCheckInDates` date. Right?

PS. Dates with time are not planned at all at the moment.

**Comment by 3nematix** [comment]
Not really, the issue in this case is that It's not possible to select check-out on someones else check-in date. Please test it with multiple reservations active.
