### ISSUE TITLE
Range allows to select after Check-In Check-out dates

### ISSUE THREAD

**Issue by 3nematix** [benitolopez/hotel-datepicker#155]
https://i.gyazo.com/9c10c4996924dc9fc23f88cfff9a58df.mp4

Config:

```
clearButton: true,
autoClose: false,
minNights: 1,
selectForward: true,
preventContainerClose: true,
disabledDates: disabled_dates,
noCheckInDates: no_check_in_dates,
noCheckOutDates: no_check_out_dates,
```

![image](https://user-images.githubusercontent.com/46891372/213377031-77947d50-440f-44ea-9037-69157cb41dbd.png)

**Comment by benitolopez** [comment]
Hi,

I'm sorry, but I don't understand the issue from your video.

I see that you can select from 2023-01-19 to 2023-01-22 which is correct.
And you can select from 2023-01-21 to 2023-01-22, which is also correct.

What is the issue?

**Comment by 3nematix** [comment]
as you can see 20-21 is someones else reservation for one night. I noticed that it does let you to reserve when there's only one night stay so there's no disabled dates between the ranges you select. In this case only 19-20 should be valid, definitely not 19-22

**Comment by benitolopez** [comment]
Wait, you probably misunderstood the meaning of those options. `noCheckInDates` only means that you cannot use it as a check-in. It does not mean that this date cannot be in the middle of a range. The same applies to `noCheckOutDates`: it only means that it cannot be used as a check-out.

To mark dates as unavailable (because they are already occupied by a reservation, for example), you must use `disabledDates`. Those cannot be in the middle of a reservation.

2023-01-19 to 2023-01-22 is valid because there are no disabled dates inside that range. And 2023-01-19 is not a disabled check-in and 2023-01-22 is not a disabled check-out. So this is a correct date range.

**Comment by 3nematix** [comment]
Sorry, I'm a bit lost right now, could you provide the correct config for these dates to work correctly? Maybe I'll get the point

Used config:
```
disabled_dates: Array [ "2023-01-23", "2023-01-24" ]
no_check_in_dates: Array [ "2023-01-22", "2023-01-20" ]
no_check_out_dates: Array [ "2023-01-25", "2023-01-21" ]
```

https://i.gyazo.com/6a7ab9890a2a34f53db5f3eae4286106.mp4

**Comment by benitolopez** [comment]
Just use only the `disabled_dates` option:

```
disabled_dates: [ "2023-01-20", "2023-01-21", "2023-01-22", "2023-01-23", "2023-01-24", "2023-01-25" ]
```

And nobody will be able to book a date on those dates. If you want to allow the check-out on a disabled date (so in this example only "2023-01-20"), then set also the `enableCheckout` to true:

```
disabled_dates: [ "2023-01-20", "2023-01-21", "2023-01-22", "2023-01-23", "2023-01-24", "2023-01-25" ],
enableCheckout: true
```

In this example, I'm considering that "2023-01-20", "2023-01-21", "2023-01-22", "2023-01-23", "2023-01-24", "2023-01-25" are all disabled/reserved dates. For example, a reservation from 2023-01-20 to 2023-01-26. Please note that I wrote 2023-01-26 and not 2023-01-25. In other words, if a reservation ends on the morning of day X, the disabled date is the day before the X date. 

Here are a couple of examples to explain it better.

Reservation from "2023-01-20" (check-in) to "2023-01-23" (check-out):

```
disabled_dates: [ "2023-01-20", "2023-01-21", "2023-01-22" ]
```

Reservation from "2023-01-20" (check-in) to "2023-01-21" (check-out):

```
disabled_dates: [ "2023-01-20" ]
```

**Comment by 3nematix** [comment]
Damn, spent few days trying to implement it myself :D 

thanks buddy! works like a charm.
