### ISSUE TITLE
Strange highlight on disabled dates focus?

### ISSUE THREAD

**Issue by 3nematix** [benitolopez/hotel-datepicker#156]
Due to complexity I don't really want to add a lot of CSS selectors  to fix it on my own, because there's a lot of cases. 
I have overridden today styles to a white background and etc, I have to manually check if there are any reservations today and if there's I have to apply other bg-color and more. And this :focus really makes everything so much harder.

For example today (with no reservations), Today (check-in), Today (check-out) and etc...

https://i.gyazo.com/5a928e4b6b58b03015543f739e1ae9f7.mp4

**Comment by benitolopez** [comment]
The focus highlight is for accessibility reasons. If you don't like it, the only solution is to build your own CSS from scratch. Please remember that the CSS provided is just an example, and support for customizations is not provided.
