### ISSUE TITLE
Feature Request: extra text in calendar day cells

### ISSUE THREAD

**Issue by solidaverage** [benitolopez/hotel-datepicker#157]
A common use case for hotels is to display the lowest rate (money amount) for each day directly in the date picker calendar.

Would this be something you'd consider adding?

Thanks

**Comment by benitolopez** [comment]
Hello,

Since 4.6.0 there's a new option "extraDayText" that allows you to define a function and print what you need. Check the demo for more info.

**Comment by solidaverage** [comment]
Thank you very much.
