### ISSUE TITLE
CSS dont apply on React  18.2.0

### ISSUE THREAD

**Issue by SaadEla** [benitolopez/hotel-datepicker#158]
**Modules Imported:**

import * as fecha from "fecha";
import HotelDatepicker from "hotel-datepicker";
import "hotel-datepicker/dist/css/hotel-datepicker.css";

**Package json**

    "fecha": "^4.2.3",
    "hotel-datepicker": "^4.6.0",
    "react": "^18.2.0",

**Problem**

The majority of date Picker css is not Applied
![image](https://user-images.githubusercontent.com/45466806/218316045-5d457449-c944-4c99-9e81-ab7c1e407dae.png)

**Expected Result**

DatePicker with css Render as in the demo
![image](https://user-images.githubusercontent.com/45466806/218316081-bcbdec10-a2d8-411b-98ea-404a435d5a1f.png)

**Comment by benitolopez** [comment]
Hello,

Please share an URL where I can see the problem. Otherwise, from here, I can't help you.

Best,
Benito

**Comment by SaadEla** [comment]
I figured it Out, its overided by some others plugins css. I think it would be good if the style were more scoped.

If u have other solutions, thanks in advance !

**Comment by benitolopez** [comment]
You can develop your CSS starting from the original one. Please remember that the original CSS is just a starting point. It is not meant as a definitive solution.
