### ISSUE TITLE
Use CSS Variables

### ISSUE THREAD

**Issue by thekendog** [benitolopez/hotel-datepicker#161]
Would be nice if we could easy change the colors on the picker.  Instead of using hardcoded colors, CSS variables would make it much easier to change the look.

**Comment by benitolopez** [comment]
Hello,

You can compile the .scss files. Colors are not hardcoded there:
https://github.com/benitolopez/hotel-datepicker/blob/main/src/sass/_variables.scss

Anyway, the CSS included in the library is just an example, I always recommend creating your own style for the datepicker. It is not a definite solution but a starting point.
