### ISSUE TITLE
Is it possible to pass valuable to stateDate?

### ISSUE THREAD

**Issue by Mandyli100** [benitolopez/hotel-datepicker#164]
Is it possible to pass valuable to stateDate? Or dynamically set startDate after var datepicker = new HotelDatepicker(input, { }. For example if I can pass a value for startDate in a hidden input field? 
var inputDateStart = document.getElementById('dateStart');
				var datepicker = new HotelDatepicker(input, {
                
                        inline: true,
						format: "DD/MM/YYYY",
                        clearButton: true,
                        submitButton: true,
                        topbarPosition: "bottom",
                        submitButtonName: "reserve",
						noCheckOutDaysOfWeek: ['Saturday', 'Sunday'],
						noCheckInDaysOfWeek: ['Saturday', 'Sunday'],
                    }
                );
				datepicker.datepicker('startDate', inputDateStart);

**Comment by benitolopez** [comment]
The `startDate` must be passed when initialising the datepicker. You can't change it later.
