### ISSUE TITLE
min_date and disabled dates

### ISSUE THREAD

**Issue by 3nematix** [benitolopez/hotel-datepicker#165]
Hi, I've just noticed a small, but important bug. So let's say that today is the 3rd of May, and we have some disabled dates starting from May 31. So I think that the datepicker shouldn't let to choose from the dates from May 3 - May 31 because the selection wouldn't make any sense, the user still won't be able to check-in and out in the timestamp due to min_stay (30 nights)

![image](https://user-images.githubusercontent.com/46891372/236040303-e5b47956-d3a4-41b8-bd89-29516ec3b1f9.png)

Doesn't make sense, right?

![image](https://user-images.githubusercontent.com/46891372/236040411-306b039f-6db9-4f9a-af85-bf2a7d6928e3.png)

**Comment by benitolopez** [comment]
Yes, I confirm. Fixed in 4.6.1

**Comment by 3nematix** [comment]
Thank you for your quick response :)
