### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 3nematix** [benitolopez/hotel-datepicker#166]
Hello,

I have a situation where properties require monthly payments, which equals 30 days. However, I'm facing a challenge in enabling users to select a specific duration in days. Currently, the minimum duration is set to 30 days, but users can still select durations like 31, 52, and so on. Is there a feasible solution to restrict their selection to only 30, 60, or 90 days? Essentially, I want users to be able to rent a place for exactly one or two months, without allowing durations shorter or longer than that.

In essence, I'm looking for a way to implement a fixed time period in terms of days.

**Comment by benitolopez** [comment]
Hello,

As you know, there's no such option. But it is interesting, and I will try to add it.
However, I'm pretty busy these days, so I don't have an ETA. And I cannot guarantee anything.

Best,
Benito

**Comment by 3nematix** [comment]
Thank you for your response. 

Where could I donate to your project?

**Comment by benitolopez** [comment]
Thank you for the offer, really appreciate it! But I'm not accepting donations at the moment :)

**Comment by 3nematix** [comment]
Hi, just wanted to follow-up and ask if there would be any updates on this in the future?

Thanks!

**Comment by benitolopez** [comment]
Hello, as I said before I don't have an ETA for this and, most important, I can't guarantee that this feature will be included in the near future

**Comment by benitolopez** [comment]
Added in 4.7.0
