### ISSUE TITLE
clearButton does not display in topBar when clearButton: true and showTopbar: true

### ISSUE THREAD

**Issue by dieguiviti** [benitolopez/hotel-datepicker#168]
Code follows documentation, topbar displays just fine, but hmtl of clear button does not seem to even render. 

UI: 
<img width="593" alt="Screenshot 2023-05-29 at 16 14 11" src="https://github.com/benitolopez/hotel-datepicker/assets/40903110/5226570a-9292-4ea6-85f8-e1d1586fec2a">

code:
<img width="603" alt="Screenshot 2023-05-29 at 16 14 59" src="https://github.com/benitolopez/hotel-datepicker/assets/40903110/7e112b5a-7a9a-4bfd-a912-72eeb07986c4">

Html rendered:
![image](https://github.com/benitolopez/hotel-datepicker/assets/40903110/1b09468d-3c15-4a33-a0e8-ac0ba6ccc228)

Manipulated styles
`.datepicker {
    z-index: 999;
    font-family: Arimo,sans-serif;
}
.datepicker__month-day--selected,
.datepicker__month-day--first-day-selected, 
.datepicker__month-day--last-day-selected,
.datepicker__month-day--hovering {
    background-color: #B2E6EE;
    color: #3A6AEA;
}
.datepicker__month-day--today {
    background-color: transparent;
    color: #3A6AEA;
}
.datepicker__tooltip {
    background-color: #3A6AEA;
    color: #FFFFFF;
}
.datepicker__tooltip:after {
  border-top: 4px solid #3A6AEA;
}
.datepicker__month-button {
	background: transparent;
}
.datepicker__month-button:hover {
    background-color: transparent;
    color: black;
}
.datepicker__month-day--disabled:after {
    display: none;
}
.datepicker__month-day--disabled {
    color: #F79CA3;
}`

**Comment by dieguiviti** [comment]
Hey Benito!

Just fixed it. Was pulling the script from a local install. Version 4.3.0

Now I am pulling from latest major version of JSDelivr

Best,

Diego

**Comment by benitolopez** [comment]
Thank you for confirming.

Best,
Benito
