### ISSUE TITLE
bug when "enableCheckout = true" & "autoClose=fale"

### ISSUE THREAD

**Issue by wsteel** [benitolopez/hotel-datepicker#17]
when option set "enableCheckout = true" & "autoClose=fale" ,  
first , select normal range is ok , 
then you can select a disabled date , and make a disabled range .

before:
![before](https://user-images.githubusercontent.com/20486291/32821298-94b851b4-ca0d-11e7-942e-b900be63b253.jpg)

after:
![after](https://user-images.githubusercontent.com/20486291/32821319-acc5285e-ca0d-11e7-88fa-4424d0373b4c.jpg)

**Comment by benitolopez** [comment]
Yeo, I confirm. Fixed in v.3.0.1.
