### ISSUE TITLE
Feature request - getRange(d1, d2)

### ISSUE THREAD

**Issue by 3nematix** [benitolopez/hotel-datepicker#171]
Hey there, I've come across a problem. I need to work with range1 and range2. Here's the situation: we have a string that displays a range of dates as date1 - date2. When someone clicks on the first date, I should be able to get that date (d1) and update the string. The datepicker actually displays it here, so we should add a method for it:

![eae7460a4d7e55be17da631d7ce0219a](https://github.com/benitolopez/hotel-datepicker/assets/46891372/82a7f439-7039-4409-b8f1-034cc3511660)

**Comment by benitolopez** [comment]
There's not something like that available. And it is not planned at the moment. However, feel free to open a PR with a working solution.

Best,
