### ISSUE TITLE
disabledDates not working

### ISSUE THREAD

**Issue by KabilanV** [benitolopez/hotel-datepicker#172]
Hi thanks for developing this amazing plugin.

I'm facing an issue when using disabledDates option. Although the dates are added, it's not showing the 'x' on the dates.
Please Help.

Here's my code:

```
let blockedDates = ['07-09-2023', '09-09-2023']
var hdpkr = new HotelDatepicker(document.getElementById("checkin"), {
            disabledDates: blockedDates,
            inline: true,
            format: 'DD-MM-YYYY',
            startOfWeek: 'monday',
            maxNights: 10,
            startDate: formatDate(new Date()),
            endDate: endDateGen(new Date()),
            selectForward: true,
            enableCheckout: true
        });
```
![image](https://github.com/benitolopez/hotel-datepicker/assets/19512500/f7d61262-54b1-426a-a912-36b029709f89)

I'm using the following versions:
fecha@4.2.3
hotel-datepicker@4.6.1

**Comment by KabilanV** [comment]
Issue solved by changing the date format from `DD-MM-YYYY to YYYY-MM-DD` just for **disabledDates**

Hope this will be fixed in a newer version :) 

Thanks.

**Comment by benitolopez** [comment]
Hi,

**disabledDates** (and other options) require that format. This is specified here:
https://github.com/benitolopez/hotel-datepicker#disableddates
