### ISSUE TITLE
tabindex on parent element breaks datepicker

### ISSUE THREAD

**Issue by alexbajoris** [benitolopez/hotel-datepicker#173]
Hello,

Great datepicker. However, i've run into a strange issue where if a parent element has a tabindex of any value the datepicker closes when clicking on the dates.  You can recreate with just this . . .

```
<div tabindex="0">
    <input type="text" value="" id="test" autocomplete="off">
    <script>
    const dateInput = document.getElementById('test');
    var datePicker = new HotelDatepicker(dateInput);
    </script>
  </div>
```

**Comment by benitolopez** [comment]
Is there a reason why you set that tabindex in the container? It conflicts with the accessibility events of the datepicker, you have to remove it. The datepicker already opens by putting the input in focus.
