### ISSUE TITLE
Flexible minNights

### ISSUE THREAD

**Issue by Maxximus007** [benitolopez/hotel-datepicker#175]
Hi,

First of all: thank you for your continuous support on your project! 

I have the following feature request, and this might be of interest for others as well. Currently minNights is a fixed value for the datepicker shown. In several cases, the minNight values could be different for different seasons/dates. Would it be feasible to have an override for minNights starting from a certain date?

This could help with another issue with minNights as well: if the free period between 2 dates is shorter than minNights, it becomes unselectable.

**Comment by benitolopez** [comment]
Hello,

This is already on my agenda, but I didn't have the time to implement it. And I won't have time to do that anytime soon.

Regarding the issue, can you be more specific? With a real example?
