### ISSUE TITLE
When select the dates from the picker need to assign both check-in and check-out dates separately to another input field values

### ISSUE THREAD

**Issue by Nuwananj** [benitolopez/hotel-datepicker#176]
In my case, there are two input fields as below,

<input type="text" name="eZ_chkin" :value="formattedCheckin"/>

<input type="text" name="eZ_chkout" :value="formattedCheckout"/>

need to assign selected Check-in date to "formattedCheckin" value and Check_out date to "formattedCheckout" value, how to do that.

**Comment by benitolopez** [comment]
Hello,

Sorry, but this repo is for reporting bugs only. I suggest you use StackOverflow if you need help with custom code.

Just as a quick example (can't help you with that), here I set the value of two hidden fields when a range is selected:
https://github.com/wp-hotelier/wp-hotelier/blob/main/assets/js/frontend/hotelier-init-datepicker.js#L96
