### ISSUE TITLE
Small Questions

### ISSUE THREAD

**Issue by ALTITUDE-DEV-FR** [benitolopez/hotel-datepicker#177]
Hi,  Great plugin ! 

Small question, how to disable a month or a years complete ? ex: 2023 January is available, si Fev is not available and Mars is available ?

Thanks ;)

**Comment by benitolopez** [comment]
Hello,

This is not possible at the moment. The datepicker accepts only an array of dates: https://github.com/benitolopez/hotel-datepicker?tab=readme-ov-file#disableddates

**Comment by benitolopez** [comment]
I'm closing this because it is not a bug. However, I noted the feature request.
