### ISSUE TITLE
Add disabled dates after initialize, and preload date range from session storage

### ISSUE THREAD

**Issue by bigmmind** [benitolopez/hotel-datepicker#179]
Hi Benito,
Thank you so much for your library it is superb!

I have a few questions that I can't see an answer to in the docimentation:

1. Is it possible to preload the date range, I was able to do it with flatpickr by loading dates from session storage, but struggle to do it with Hotel Datepicker
2. Is it possible to first initialize the date picker and after that pass an array of disabled dates? I am loading disabled dates from API and it takes some time for it to load, plus I may need an option to reload booked each 5 minutes if the user remains on the page. Currently I can only see how to load the disabled dates when initializing initially.
3. How can I get the selected start and end date?

Thanks a lot in advance!

**Comment by benitolopez** [comment]
Hello,

1. Not sure what you mean by "preload the datepicker", but this does not seem to me to be an issue with the datepicker, but a problem with your custom code. Unfortunately, I am unable to help you.
2. It is not possible.
3. You already have the value. It's the value of the input. You can use some JS to extract the start and the end date from the input value.

Please remember that this repo is for reporting bugs.

**Comment by bigmmind** [comment]
Thanks!
