### ISSUE TITLE
Month change event like jquery ui datepicker

### ISSUE THREAD

**Issue by sarathiscookie** [benitolopez/hotel-datepicker#18]
I am developing a hotel room booking system. For that I am planning to use your wonderful plugin. I have to show in seasons and holidays in calendar. That means, winter starts from Nov 15 to April 25 & Summer starts from May 15 & Oct 10. In between these seasons some days are holidays. In calendar, I need to show holidays and not season days as disabled in calendar. Is it possible with this plugin? Do this plugin support next month change event like jquery ui datepicker.

**Comment by benitolopez** [comment]
The plugin doesn't emit events. It's something you need to add yourself (you can for example add a listener to the next/prev buttons or check the value of the input).

Regarding the holidays, you can pass disabled dates to the datepicker, see the readme and the demo.

PS. Please use this repo to report **bugs** only.
