### ISSUE TITLE
Datepicker hangs at height:0 

### ISSUE THREAD

**Issue by Steinweber** [benitolopez/hotel-datepicker#183]
When I click on the input field of the data picker, it opens normally. If I use the "Close" button, I can also open the date picker again. 
But if I click outside the input field, the datepicker disappears, gets the class datepicker--closed, but keeps the style height:0 and does not get the value display: none. From this point on, the datepicker can no longer be opened. The classes change when it is opened, but the style height:0 means that nothing is displayed. 

This can be fixed with a few lines. But I would like to fix the cause of the problem. 
```
input.addEventListener('afterClose', (e) => {
        if(datepicker.datepicker.style.height !== null){
            datepicker.datepicker.style.height = null;
            datepicker.datepicker.style.display = 'none';
        }
    });
```

**Comment by benitolopez** [comment]
Is this something that happens in the demo?
https://lopezb.com/hoteldatepicker/

If so, can you give me more details? I haven't figured out how to reproduce the problem.
If not, please verify that you implemented the datepicker correctly and share the URL where I can see it in action

**Comment by Steinweber** [comment]
I have found my mistake. With animationSpeed I assumed a number. If you put a number instead of the expected string, there is no error in the console, but the datepicker only opens once.

https://codepen.io/MaxDau/pen/ZEZyOON

**Comment by benitolopez** [comment]
Ok, then, I'll close this. As per documentation, that option requires a string: https://github.com/benitolopez/hotel-datepicker?tab=readme-ov-file#animationspeed
