### ISSUE TITLE
Bug: Close button after clean or deselecting disabled

### ISSUE THREAD

**Issue by Steinweber** [benitolopez/hotel-datepicker#184]
Open the calendar, select a date (do not select an enddate):
Now the close button is disabled. 
- Click on Clear
- Deselect the first selected date again

The Close button remains disabled.
Tested in the demos and the problem is there too.

**Comment by benitolopez** [comment]
Which demo exactly? Because I can't find a demo with the close and clear buttons as you said.

**Comment by Steinweber** [comment]
I tested from "Maximum number of nights: 5" and the next 4 -5 demos

**Comment by benitolopez** [comment]
There isn't a clear button on those datepickers. You said, "Click on Clear".

Anyway, I understand what you mean now. It happens every time you deselect the first date.

**Comment by Steinweber** [comment]
Yes, there is no clear button in the demos. You can only see the effect there if you deselect it. Here is a demo with a clear button.

https://codepen.io/MaxDau/pen/mdgwEVw

**Comment by benitolopez** [comment]
Fixed in 4.7.2
