### ISSUE TITLE
Unexpected behavior: setRange

### ISSUE THREAD

**Issue by Steinweber** [benitolopez/hotel-datepicker#186]
I wanted to keep several datepickers / calendars synchronized. I noticed that the date was not correct with setRange(dateObject, dateObject). With setRange (string, string) the result was correct. A look at the code shows that the dateObject is used and manipulated directly, which makes it useless for me for further use. 

It might be better to recreate the dateObjects in the datepicker to avoid such unexpected results.

https://github.com/benitolopez/hotel-datepicker/blob/e3c490adc4fb5c9dcab7e355ea4715b40e291af2/src/js/hotel-datepicker.js#L2967
```
        else {
          d1 = new Date(d1.getTime());
          d2 = new Date(d2.getTime());
        }
```

**Comment by benitolopez** [comment]
Ok, fixed in 4.7.3
