### ISSUE TITLE
hotel-datepicker issues with bootstrap 5.3

### ISSUE THREAD

**Issue by orionseye** [benitolopez/hotel-datepicker#189]
I am migrating from material.css to bootstrap 5.3 and experience some rendering issues of the datepicker.
While with material.css everything worked fine, with Bootstrap it happens that the datepicker (sometimes) is not showing up at all.
What i mean is, clicking several times into the input which triggers the datepicker (while trying to test different date range) all of the sudden, it stops showing up.
Removing class 'datepicker' resolves the issue. 
It would make sense to rename the class, as both hotel-datepicker & Bootstrap share the same class which causes conflicts
Do you people experience something similar?

**Comment by benitolopez** [comment]
I understand. Unfortunately, for backward compatibility reasons I cannot rename the class now. But I can add a new option that allows you to define the datepicker class. It should solve your issue.

**Comment by orionseye** [comment]
Thanks Beni, that would be very helpful. Nice app, love it :)

**Comment by orionseye** [comment]
@benitolopez just as a hint: i inspected the whole issue again and it seems that somehow the dynamic style of the hotel-datepicker conflicts with Bootstrap 5,x
Actually the datepicker opens but not visible due to missing height in css.
Open/closing several times, all of the sudden the css generated assigns no height to the datepicker with "style="height: 0px;"

```
<div id="datepicker-datespick" style="height: 0px; transition: height 0.5s ease 0s;" class="datepicker datepicker--topbar-top datepicker--topbar-has-close-button  datepicker--closed" tabindex="0"><div class="datepicker__inner">
...
```

**Comment by benitolopez** [comment]
Added in 4.8.0
