### ISSUE TITLE
like it, some way to allow empty end date range

### ISSUE THREAD

**Issue by mckaygerhard** [benitolopez/hotel-datepicker#19]
hi, i like your pure js "no jquery" implementation of date range picker

there's some way to allow user choose starter date and let empty the end of the range optionally?

if i must change the code there's no problem, i try but please i need it.

**Comment by benitolopez** [comment]
Hi,

This is not possible. This is a daterange datepicker so an end date is mandatory. You can set the first default date with the `startDate` option (see the readme).

Please use this repo to report bugs only.

**Comment by mckaygerhard** [comment]
hi, logically its not posible due obviously reasons, but for a while, there's any way to do so? please some piece of code or a line to start that!

i want to use it to date range for reports but my people are very flexible in request.. lease help me to doit by my selft

**Comment by benitolopez** [comment]
I'm sorry but I don't offer support for custom code. This is not an help channel, but a place to report bugs or contribute on the project. Please understand.
