### ISSUE TITLE
Datepicker keeps setting height = 0 after closing and does not open

### ISSUE THREAD

**Issue by sarags** [benitolopez/hotel-datepicker#191]
Hi,

I'm trying to close the datepicker and hide the div that contains it in the click of one button and when scrolling the page, the problem here is that the datepicket after closing when trying to open again is getting height = 0 so it opens but it's not visible.
For exemple on the scroll function i'm using something like this

```php annotate
if (datepicker && datepicker.isOpen) {
    datepicker.close();
}
```

but when i try to open it again the height is 0, i'm missing something here ? 
If i close the datepicker by clicking outside of it or in the button it's working fine

Thank you !

**Comment by benitolopez** [comment]
Honestly, I don't know; it seems something custom to me, and this repo is for reporting bugs only. Unfortunately, I can't help you with custom implementations.

Try to add a console.log() when the datepicker closes (https://github.com/benitolopez/hotel-datepicker?tab=readme-ov-file#afterclose). Maybe, inadvertently you're calling the close() function multiple times.

**Comment by sarags** [comment]
I will try to check that, thank you :)

**Comment by benitolopez** [comment]
Yes, it can be a good idea. I'll investigate it in the next days

**Comment by benitolopez** [comment]
Added in 4.9.0
