### ISSUE TITLE
Feature suggestion: option or event on clearing the date range

### ISSUE THREAD

**Issue by haukkalasse** [benitolopez/hotel-datepicker#192]
Hi.

First of all, thanks for the great calendar component. I have been using it on many projects.

Today I had a need for an option to hook on the clear button click event. I'm aware that I could have used  `clear()` function on a button, which could have also solved the issue, but this time it was better to have it on the clear button in calendar.

I actually got around it by making my own option for it, using `onSelectRange` as guide. I made new option `onClearDatepicker` and made it run on `clearDatepicker()` function. Now I could use it in the same way as `onSelectRange` or `onDayClick` option on multiple calendars I had on the project.

So this is not necessary an issue for me, but maybe it is something that someone else might also need?

**Comment by benitolopez** [comment]
Hi,

Something like this?

https://github.com/benitolopez/hotel-datepicker/pull/193/files

**Comment by haukkalasse** [comment]
Yes, this works perfect. I tested it on my project and it works just like I wanted to use it.

Thank you for quick response.

**Comment by benitolopez** [comment]
Added in 4.10.0
