### ISSUE TITLE
Update noCheckOutDates after selected a dates

### ISSUE THREAD

**Issue by gabrielbois** [benitolopez/hotel-datepicker#195]
Hello 👋
I need to update the no checkout dates after the selection of the checkin date.
Because I need to know the checkin date to check in my API the allowed checkout dates for this date.
But when I click on a checkin date, I'm trying to change the option noChekoutDates of the calendar but nothing...
Is there an event for this ?

I show you my code to help you.

```javascript
let calendar = new HotelDatepicker(input_calendar, {
    format: 'DD/MM/YYYY',
    startOfWeek: 'monday',
    startDate: new Date(),
    noCheckInDates: [],
    noCheckOutDates: [],
    disabledDates: [],
    container: calendar_container,
    inline: true,
    hoveringTooltip: true,
    showTopbar: true,
    topbarPosition: 'bottom'
});

// I'm disabled checkin dates -> it's work
calendar.noCheckInDates = disallow_checkin_dates.split(',');

calendar.container.addEventListener('click', (event) => {
    if(event.target.matches('tbody tr td.datepicker__month-day--valid.datepicker__month-day--first-day-selected:not(.datepicker__month-day--no-checkin)')) {
        let day = event.target,
            timestamp = parseInt(day.getAttribute('time')),
            date = moment(timestamp).format('YYYY-MM-DD');

            // Call API returning an array like this  return ['2024-09-15', '2024-09-16'];
            calendar.disabledDates = ['2024-09-15', '2024-09-16'];
    }
});
``` 

EDIT POST :
Is it possible to refresh the calendar after I change the options after the init ?

Could you explain to me what i'm doing wrong ?
Thank you very much !!! 👋

**Comment by benitolopez** [comment]
Hello,

This repo is for reporting bugs only, so I can't help you with custom code. I'm sorry.

Currently, the datepicker has no method to refresh, so it has to be instantiated again.
