### ISSUE TITLE
can not select specific date

### ISSUE THREAD

**Issue by sergej-papper-itpc-vu-lt** [benitolopez/hotel-datepicker#196]
Hi,

There is some annoying bug. I can not select a specific date. In this case - 2024-09-14 (please see the screenshot, "rugsėjis" means september in our language).
![Screenshot 2024-09-02 105835](https://github.com/user-attachments/assets/936bbaae-ac98-4565-8d8d-f6c6f4ed9535)

This date should be enabled, because it is not in disabledDates array and today is 2024-09-02.

I am using the latest version of hotel-datepicker at the moment (4.11.0).

The option object look like this:
```
new HotelDatepicker(input, {
                            startOfWeek: 'monday',
                            disabledDates: disabledDates,
                            moveBothMonths: true,
                            endDate: new Date(year, month + 12, 0),
                            maxNights: 30,
                            },
                        });
```

Can you help me with this issue? Thank you.

**Comment by benitolopez** [comment]
A valid range must have at least one night, so two dates. If 2040-09-13 and 2040-09-15 are disabled, you cannot select 2040-09-14. 

Try to enable this: https://github.com/benitolopez/hotel-datepicker?tab=readme-ov-file#enablecheckout

**Comment by sergej-papper-itpc-vu-lt** [comment]
It works. Thank you :)
