### ISSUE TITLE
Clear does not reset the default text after an error.

### ISSUE THREAD

**Issue by MaxxDau** [benitolopez/hotel-datepicker#197]
clearButton: true,
minNights: 2,
maxNights: 31

Default text is: 
Please select a date range between 2 and 31 nights

1. Select and deselect one day
Text is: Date range should not be less than 2 nights

2. Select a valid range or only one day
Text is: Your stay: 10-12-2024 - 17-12-2024 (7 Nights)

3. Click clear button
Text is: Date range should not be less than 2 nights
But text should be: Please select a date range between 2 and 31 nights

Thanks for your work :)

**Comment by benitolopez** [comment]
Yes, fixed in 4.11.1.
