### ISSUE TITLE
How to get value after date picket close.

### ISSUE THREAD

**Issue by ashish8833** [benitolopez/hotel-datepicker#20]
I am use this plugin in Angular 4.x, which callback or method to get all values like startdate, enddate, nights, day after close datepicker.
Thanks.

**Comment by benitolopez** [comment]
Hi,

The methods available are visibile in the readme. The plugin doesn't emit events. 
And you can still add a listener to the input to see when it changes its value. 

https://github.com/benitolopez/hotel-datepicker/issues/4
