### ISSUE TITLE
showTopBar option is not working

### ISSUE THREAD

**Issue by surfer190** [benitolopez/hotel-datepicker#21]
## Preconditions:

Version `3.0.1` of `hotel-datepicker`
Version `2.3.1` od `fecha`
Browser `chrome` on`macOS`

Changing the `demo1` code to:

```
var demo1 = new HotelDatepicker(input1, 
				{
					autoClose: true,
					showTopbar: false
				}
			);
```

does not remove the top bar on the datepicker

![image](https://user-images.githubusercontent.com/3285222/33765289-bbe1437a-dc20-11e7-8763-dc2fd255baa4.png)

**Comment by benitolopez** [comment]
Yes, right. this was fixed in the v.3.0.2 (released right now).
