### ISSUE TITLE
MinNights of 0 is not working

### ISSUE THREAD

**Issue by surfer190** [benitolopez/hotel-datepicker#22]
A global minimum number of nights is forced to be one, ie. you cannot select the same start and end date.

## Preconditions:

Version `3.0.1` of `hotel-datepicker`
Version `2.3.1` od `fecha`
Browser `chrome` on`macOS`

Changing the `demo1` code to:

```
var demo1 = new HotelDatepicker(input1, 
	{
		minNights: 0
	}
);
```

does not allow the selection of a single date for start and end date

**Comment by benitolopez** [comment]
Yes exactly, because this is a daterange picker for hotels. And obviously at least one night is required for every stay. This is not a bug.

**Comment by surfer190** [comment]
Well, it is your decision of course but a small change could allow the datepicker be applicable for other things like airplane flights or taking leave.

Casting a wider net of use, but I guess that comes with its own problems as well.
