### ISSUE TITLE
Scroll & No weekdays bar

### ISSUE THREAD

**Issue by monopollly** [benitolopez/hotel-datepicker#23]
Hi, its really awesome. You rock)
Several suggests for calendar...

maybe you could add a "flatMode"
For example set 6 month and picker show me all 6 month one by one
I thinks its more informative and responsive, like this 
https://gyazo.com/ffca9cd0a18fb0b43d699a641f72f13d

and the second one is options like 
showWeeks
showMonth

Thanks!

**Comment by benitolopez** [comment]
Hi,

Thank you for your feedback. The purpose of this plugin is to maintain the code and the features simple as much as possible. So I'm sorry but don't expect a flat mode any time soon.

This is a date range picker designed for hotels specifically. Not a multi-purpose date range picker.
