### ISSUE TITLE
Get days name on select day?

### ISSUE THREAD

**Issue by arsistyle** [benitolopez/hotel-datepicker#26]
I need get the days name, is some option or event for this?

**Comment by benitolopez** [comment]
No, there's not an option for that. You need to calculate it yourself (you know the value of the input).

**Comment by arsistyle** [comment]
Solution for me.

`onDayClick: function () {
  var first = new Date(this.getValue().slice(0, 10)).getDay()+1;
  var last = new Date(this.getValue().slice(13)).getDay()+1;
}`

create your array with name of days and get the val depending of number of vars "first" & "last"
