### ISSUE TITLE
moveBothMonths not working and enables other prev/next buttons

### ISSUE THREAD

**Issue by russc** [benitolopez/hotel-datepicker#27]
This is an awesome datepicker and and I really want to use it, but I'm having issues with the moveBothMonths navs.....
Notice how the nav buttons that should remain disabled show up.  Is there a fix for this?
https://www.useloom.com/share/fa084cc18e064712aa6c63d7f7c9bbb8

**Comment by benitolopez** [comment]
Seems that you're not using the `moveBothMonths` at all in your demo. Did you set it to `true`?

Default is `false`:
https://github.com/benitolopez/hotel-datepicker#movebothmonths

Also, please provide a real URL. And be sure that you're using the last version of the library.

**Comment by russc** [comment]
Thanks Benito!  I was helping a friend who is implementing this and it was a version issue.
