### ISSUE TITLE
How to change color of input:active?

### ISSUE THREAD

**Issue by anykarolyne** [benitolopez/hotel-datepicker#28]
I want to change the color of the class .datepicker__dummy-input--is-active but i can't.

My vue component:
```
<template>
  <no-ssr>
    <HotelDatePicker class="color-active" :i18n="dateoptions.i18n" :format="dateoptions.format" DatePickerID="travel" @checkOutChanged="updateDateTo($event)" @checkInChanged="updateDateFrom($event)"/>
  </no-ssr>
</template>
```
My style:
```
.datepicker-label{
  font-weight: normal;
  color: #4182e0;
  display: inline-block;
  max-width: 100%;
  margin-bottom: 5px;
}
.color-active .datepicker__dummy-input--is-active{
  color: #4182e0;
}
```
The class datepicker-label is working perfectly, but when is active not working. The strange is when I inspect the elements the modification appears, but the screen continues the default color(#00ca9d). 
![foto 1](https://user-images.githubusercontent.com/7489445/34733437-8431a8f0-f54f-11e7-91d8-0e05e1beb569.jpg)

**Comment by benitolopez** [comment]
Hi,

My library doesn't have those classes, you're probably using the Vue version:
https://github.com/krystalcampioni/vue-hotel-datepicker

You should open a ticket on that repo.
