### ISSUE TITLE
Disabled Dates Styling

### ISSUE THREAD

**Issue by alfredkorn** [benitolopez/hotel-datepicker#3]
I am using your datepicker with disabledDates: [] AND enableCheckout: true.

Do you have a suggestion how to have different styling on the "enableCheckout" date and the day after the  last disabled date in a block of disabled dates?

Best look at the example attached.
![checkout_dates](https://user-images.githubusercontent.com/12958044/28998746-5dfbe9f4-79e7-11e7-8c03-7ad11bd38ef7.png)

**Comment by benitolopez** [comment]
There are already some helpers CSS classes for that:
- datepicker__month-day--first-day-selected: first selected day
- datepicker__month-day--last-day-selected: last selected day
- datepicker__month-day--checkout-enabled: disabled date but with the checkout allowed

How to style those elements it's up to you.
