### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by melbos** [benitolopez/hotel-datepicker#34]
Hi Benito, there seems to be an issue with demo. Input fields won't init date-picker's. Is there something missing in installation instruction?

**Comment by benitolopez** [comment]
The demo in my website or in the package? If you're talking about the demo in the package, you need to install the dependencies:

`npm install`

then:

`npm run watch` to start it.

To start from scratch just include the required files: https://github.com/benitolopez/hotel-datepicker#installation
