### ISSUE TITLE
minNights not consistent with calendar title/message

### ISSUE THREAD

**Issue by Rodge** [benitolopez/hotel-datepicker#36]
Very nice datepicker! However, I found a bug that would be great to have fixed: When having set minNights: N as an option where N is an integer, the calendar title/message shows "Please select a date range longer than N night", but it only needs to be longer than N-1 night(s), i.e. minimum N, not minimum N+1, nights. So when setting minNights: 1, it only needs to be longer than 0 night, not longer than 1 night.   

![image](https://user-images.githubusercontent.com/414579/36965612-78e17206-205a-11e8-8b83-3d24f9534e9f.png)

**Comment by benitolopez** [comment]
Ha yes, I get the point. I will change the text to "Please select a date range longer of at least N night".

**Comment by Rodge** [comment]
Great. Thanks!

**Comment by benitolopez** [comment]
Fixed.

https://github.com/benitolopez/hotel-datepicker/commit/900d5cd04b221c50543cf40fd106fec3245bf1c6
