### ISSUE TITLE
Day in month is disabled without a reason

### ISSUE THREAD

**Issue by dkeza** [benitolopez/hotel-datepicker#37]
I found one strange bug, that some day in month is disabled without a reason
![calendar-1](https://user-images.githubusercontent.com/12168379/37141594-cead65ac-22b5-11e8-8ff9-1acb451fd114.png)
.

Steps to reproduce:

- Go to http://lopezb.com/hoteldatepicker/
- Go to "Don't close the datepicker after selection" and click in textbox to open calendar
- Click 30.4.2018. in right calendar
- Click Right Arrow in April to go to Mai
- Click Right Arrow in left calendar, to go to April
- Click 01.05.2018. in right calendar
- Click 29.04.2018. in left calendar

Now is 30.04.2018. in left calendar disabled, and can't no more be selected.

**Comment by benitolopez** [comment]
If you check the calendar now it doesn't happen. For me, because is twelve o'clock and some minutes now. But I've seen the reported issue ten minutes ago (before twelve o'clock). This is a weird issue and it will probably take a lot of time to find a solution, because is not easy to debug. Dates in javascript are not perfect.

**Comment by dkeza** [comment]
I think it has nothing to do with Javascript dates. Bug can be reproduced simply by, firstly, selecting some date in right calendar (for example 14.04.2018.), then skip in right calendar to next month, then skip in right calendar back, and date is disabled.
When I inspect this element, I see datepicker__month-day--invalid styling added:
![calendar-2](https://user-images.githubusercontent.com/12168379/37156774-59d1f7d4-22e7-11e8-86b9-c432c844fea0.png)
When I click on some other date, 14.04.2018. stays disabled.
![calendar-3](https://user-images.githubusercontent.com/12168379/37156974-cd54f846-22e7-11e8-88bc-7b76e390a0ff.png)

It looks to me, that something wrong happens when calendar is in state with only one date selected, and then users scrolls through months.

**Comment by benitolopez** [comment]
Fixed - https://github.com/benitolopez/hotel-datepicker/commit/a7099f710800014e385234ed0e7a8910b61dc4b5
