### ISSUE TITLE
Add prices in calendar

### ISSUE THREAD

**Issue by dkeza** [benitolopez/hotel-datepicker#38]
I have added prices to calendar, but now I must adjust css to style calendar properly, because date cell is now bigger:
![calendar-4](https://user-images.githubusercontent.com/12168379/37157924-5a50fb12-22ea-11e8-81be-505827da4876.png)
Can you point me in right direction, what should I change in sass (_base.scss?), to adjust cell width?
Maybe is there also a better way to add price, instead with ```<br>``` tag?

I am not so experienced in css...

I added in constructor of HotelDatepicker two additional parameters, priceDates and priceCurrency:
```
		this.priceDates = opts.priceDates || [];
		this.priceDatesUsed = this.priceDates.length > 0;
		this.priceCurrency = opts.priceCurrency || '€';
```

**Comment by benitolopez** [comment]
I'm sorry but this repo is for bugs only. Unfortunately I can't help you with modifications or for CSS questions. I maintain this project on my spare time and right now I'm really busy. Try on stackoverflow.com.
