### ISSUE TITLE
Is inline / open by default calendar possible

### ISSUE THREAD

**Issue by ehausen** [benitolopez/hotel-datepicker#39]
Hello,

I was wondering is there a quite simple way to have the calendar inline / already open in it's place when page loads? It would save some clicks for the user and show disabled dates at glance.

**Comment by benitolopez** [comment]
No. But you can use the `open()` method as soon as you initialize the datepicker.

https://github.com/benitolopez/hotel-datepicker#open

Also, check this issue:

https://github.com/benitolopez/hotel-datepicker/issues/6
