### ISSUE TITLE
Getting selected number of nights

### ISSUE THREAD

**Issue by eguvenc** [benitolopez/hotel-datepicker#4]
How can i get the selected number of nights from api when user pick the date.

Thanks.

**Comment by benitolopez** [comment]
You can calculate it yourself. You already have the selected days (the value of the input) so you can write a JS function that calculates the number of nights.

However, I will try to add a public method for that in the next weeks.

**Comment by eguvenc** [comment]
Thanks but, is there any solution for the onSelect event to calculate the nights i need a select handler.

**Comment by benitolopez** [comment]
No, there's not an onSelect event. And probably I will not add such function in the future. The purpose of this plugin is to maintain the code and the features simple as much as possible. I’m not aware of a good and cross browser JS vanilla alternative to the equivalent trigger() jQuery function. So I would need to include an external library like EventEmitter only for that. I don’t want it.

But again, you already have the possibility to know when the selection fires: when the input changes his value.

Anyway, I'm open to pull requests.

PS. Added the new getNights() method.

**Comment by eguvenc** [comment]
Thanks.
