### ISSUE TITLE
Inline calendar (for mobile)

### ISSUE THREAD

**Issue by Reached** [benitolopez/hotel-datepicker#40]
First of all, great job on this datepicker :)!

Have you considered an optimization for mobile where the date picker would be inline instead of you having to tap to open it? Perhaps even stack the calendar months on top of each other so the user has to tap less. What do you think?

**Comment by benitolopez** [comment]
Right now only one month is shown when the screen is less than 480px. Unfortunately is quite difficult to recognize a mobile device (http://www.stucox.com/blog/you-cant-detect-a-touchscreen/). So my choice was to make a responsive datepicker and nothing else. 

However, you can use the `open()` method to open the datepicker. So you can write some custom code to recognize a mobile device (this is a non-perfect example https://github.com/benitolopez/hotel-datepicker/blob/master/src/js/hotel-datepicker.js#L1503) and then open the datepicker automatically.

I don't want to include this option in the library for a simple reason: it will be really difficult for me to maintain the code. There are a lot of problems related to mobile devices and I'm sure there will be a lot of borderline issues.

But again, there is already an `open()` method and you can stack the months with some CSS.
