### ISSUE TITLE
Can't insert to container div

### ISSUE THREAD

**Issue by avatec** [benitolopez/hotel-datepicker#44]
I've trying to add calendar to div#calendar-container without luck.

As option:
```
var datepicker = new HotelDatepicker(document.getElementById('calendar-input'), {
		format: 'DD-MM-YYYY',
		separator: '|',
		startOfWeek: 'monday',
		showTopbar: false,
		autoClose: false,
		container: '#calendar-container'
});
```

Without container works on input fine.
JS Console give me an error:

TypeError: this.parent.insertAdjacentHTML is not a function. (In 'this.parent.insertAdjacentHTML("beforeend",t)', 'this.parent.insertAdjacentHTML' is undefined)

`<div id="calendar-container"></div>`
is present in html

Any idea ?

EDIT: I found solution. There must be an object instead of id name:
```
...
container: document.getElementById('#calendar-container')
...
```

**Comment by benitolopez** [comment]
Yes, you need to pass a DOM element, not a selector.
