### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [benitolopez/hotel-datepicker#47]
Good day @benitolopez  I am a graphic designer and an open-source enthusiast and i would like to propose a logo design for your nice project as a gift for free. I just need you permission first before I begin my design. Thanks and best regards! - Tobaloidee

**Comment by benitolopez** [comment]
Thank you for the kind offer but a friend of mine is already working on it. Thank you again!

**Comment by Tobaloidee** [comment]
okay Sir. Thanks for the response..best regards again..
