### ISSUE TITLE
Fecha variable problem

### ISSUE THREAD

**Issue by avatec** [benitolopez/hotel-datepicker#48]
[Error] ReferenceError: Can't find variable: fecha
	setFechaI18n (hotel-datepicker.js:106)
	getDateString (hotel-datepicker.js:182)
	compareMonth (hotel-datepicker.js:1045)
	init (hotel-datepicker.js:237)
	HotelDatepicker (hotel-datepicker.js:70)
	Kod globalny (script.js:1)

**Comment by benitolopez** [comment]
Did you include fecha on your page?

https://github.com/benitolopez/hotel-datepicker#installation

**Comment by avatec** [comment]
Ok now works - my mistake. Thank You
