### ISSUE TITLE
"getValue()"  Sample usage

### ISSUE THREAD

**Issue by emresaracoglu** [benitolopez/hotel-datepicker#49]
Hello,

How do I get these dates if the user has determined the dates?
How to use this method , can you give me an example?

Thank you!

> getValue()
> 
> This function is called when the picker gets the date range string from the input.

**Comment by benitolopez** [comment]
You always have the value of the selected dates: it's the value of the input. So you can use some Javascript to get the value, you don't need that method.

Anyway, you can use that `getValue()` in this way:

```js
var hdpkr = new HotelDatepicker(document.getElementById('input-id'));
var get_dates_button = document.getElementById('button-id');

get_dates_button.addEventListener('click', get_dates);

function get_dates() {
	console.log(hdpkr.getValue());
}
```

But the real reason of that function is the possibility to modify the values before to set them:

```js
var hdpkr = new HotelDatepicker(document.getElementById('input-id'), {
	getValue: function() {
		// do whatever you want here
		return '2018-11-04' + ' - ' + '2018-11-08';
	}
});
```

**Comment by emresaracoglu** [comment]
Thank you very much for your reply. I think I need a button to use the code in your answer. But I don't have any button.  Isn't there a way to write dates to the console without a button?

This is my code:
```
var input = document.getElementById('rentDatesRequest');
var get_dates_button = document.getElementById(' *** no button ** ');
	get_dates_button.addEventListener('click', get_dates); 
	function get_dates() {
		console.log(input.getValue());
	}
	var datepicker = new HotelDatepicker(input, {
		selectForward: true,
		format: 'DD-MM-YYYY',
		startOfWeek: 'monday',
		autoClose: false,
		i18n: {
			[....]
		}
	}); 
	$('input[name="rentDatesRequest"]').daterangepicker();
```
 
![asdasd](https://user-images.githubusercontent.com/297968/42543300-e3af889e-84b3-11e8-84fe-493ac6cb7006.png) 

Again thank you!

**Comment by emresaracoglu** [comment]
Thank you very much for your reply. I think I need a button to use the code in your answer. But I don't have any button.  Isn't there a way to write dates to the console without a button?

This is my code:
```
var input = document.getElementById('rentDatesRequest');
var get_dates_button = document.getElementById(' *** no button ** ');
	get_dates_button.addEventListener('click', get_dates); 
	function get_dates() {
		console.log(input.getValue());
	}
	var datepicker = new HotelDatepicker(input, {
		selectForward: true,
		format: 'DD-MM-YYYY',
		startOfWeek: 'monday',
		autoClose: false,
		i18n: {
			[....]
		}
	}); 
	$('input[name="rentDatesRequest"]').daterangepicker();
```
 
![asdasd](https://user-images.githubusercontent.com/297968/42543300-e3af889e-84b3-11e8-84fe-493ac6cb7006.png) 

Again thank you!
cc @benitolopez

**Comment by benitolopez** [comment]
Yes you can use whatever you want in your code, that was just an example. You can use a function, other events, etc.

You can also use the `onSelectRange` option: 
https://github.com/benitolopez/hotel-datepicker#onselectrange

Sorry if I'm not precise enough, but this repo is for reporting bugs only. For usage or JS related questions please use [stackoverflow](https://stackoverflow.com/).

**Comment by emresaracoglu** [comment]
I have one last question. 
When I use this, only the console is written: "_Date range selected!_".
I can't get the selected date. That's the point I'm wondering. How the selected date can be retrieved.

Of course I can ask StackOverflow but I think you can give the best answer. Because you are the author of this :)

**Comment by benitolopez** [comment]
As I said above, you can just get the value of the input (with JS):

```js
onSelectRange: function() {
    console.log(document.getElementById('your-input-id').value);
}
```

**Comment by emresaracoglu** [comment]
Definitely. **Thank you for your time.**
cc @benitolopez
