### ISSUE TITLE
Month button should be disabled if min/max date is reached

### ISSUE THREAD

**Issue by Gummibeer** [benitolopez/hotel-datepicker#50]
The buttons get a disabled class if both months are following each other. But they should also get this class if the min and max date is reached. The buttons won't do anything, so they also could get hide.

**Comment by Gummibeer** [comment]
Like in your demo - July is the first available month but the arrow to the left/prev is still visible. 
![download 85](https://user-images.githubusercontent.com/6187884/42864687-989c1160-8a67-11e8-8ab6-ef4fdf4f46e6.png)

**Comment by benitolopez** [comment]
Merged, thank you very much.
