### ISSUE TITLE
Impossible dates are clickable

### ISSUE THREAD

**Issue by Gummibeer** [benitolopez/hotel-datepicker#52]
I require at least 5 nights and have a time frame of 3 days between two disabled dates - it's possible to click them for start but not to end the selection.
In my opinion the selection should stop on every click - independent of valid or not. And a nice to have would be to mark the dates that are impossible to book, because of minNights and available nights, as such with a new CSS class.

**Comment by benitolopez** [comment]
It should be fixed now.

https://github.com/benitolopez/hotel-datepicker/commit/d37a1c603d18ce6c06ca32a323c9a33106d30326

**Comment by Gummibeer** [comment]
Looks good! :)
