### ISSUE TITLE
Buttons don't disable on mobile

### ISSUE THREAD

**Issue by Gummibeer** [benitolopez/hotel-datepicker#53]
On mobile (just one calendar visible) the buttons keep visible all the time. Even if in first/last month.
It should be like on desktop and disable the previous/next button if in first/last month.

**Comment by benitolopez** [comment]
Buttons are visible also on desktop devices (prev in first month and next on the last month), it's not something related to mobile devices. Honestly, I don't think that it is a real issue. Anyway I'm open to suggestions or pull requests.

**Comment by Gummibeer** [comment]
It was added by myself in #50 - I will investigate it.
