### ISSUE TITLE
Conditional required nights (opposite of #52)

### ISSUE THREAD

**Issue by Maxximus007** [benitolopez/hotel-datepicker#54]
Hi,

The solution as offered in [#52](https://github.com/benitolopez/hotel-datepicker/issues/52) is a good one, but I'm looking for another option. Would it be possible to have the end date clickable even it is lower than the required number of nights?

So if there is an availability of 3 nights, but required nights is 5, I'd like to lower the required nights to 3 for that period- and make it possible to select an end date.

That would help to get a better fill rate.

**Comment by benitolopez** [comment]
No this is not possible. It's really hard to handle something like that. If you accept 3 nights you should use 3 minimum required nights, not 5.
