### ISSUE TITLE
Event listner on update date picker (when user don't close datepicker windows)

### ISSUE THREAD

**Issue by khoude24** [benitolopez/hotel-datepicker#57]
You have an event for `close` but can you add a Event Listner when date selection change? I need to trigger an event when the user change the date without close the calendar.  

I try `input.addEventListener('change', function () ` but its not working. Thanks

**Comment by benitolopez** [comment]
There is already an event for that: `onSelectRange`

See the readme: https://github.com/benitolopez/hotel-datepicker#onselectrange

You can see an example in the demo (last datepicker): http://lopezb.com/hoteldatepicker/
