### ISSUE TITLE
One month displayed

### ISSUE THREAD

**Issue by luntik4344** [benitolopez/hotel-datepicker#60]
Hello.
Is it possible somehow to display only only month without "next"?
The example is in attachment.
Thank you!
<img width="165" alt="screenshot at oct 04 00-57-52" src="https://user-images.githubusercontent.com/15948101/46441906-a1d2a000-c770-11e8-844b-6e08a6fff08f.png">

**Comment by benitolopez** [comment]
Hi,

Please use this repo to report bugs only. Use stackoverflow or similar to ask questions.

To display one month only you need to hide the other with CSS.
