### ISSUE TITLE
Mininum number of nights in a range of date

### ISSUE THREAD

**Issue by khoude24** [benitolopez/hotel-datepicker#61]
I have a very specific problem. In my case, I can have a minimum of night for an selected range of date. 

Example, between  2018-10-01 and 2018-10-15, user MUST select a minimum of 3 nights, otherwise, they have no minimum of nights.  Can I do something to do this with your plugin?

**Comment by benitolopez** [comment]
Hi,

No unfortunately this is not possible. No conditional minimum nights.
