### ISSUE TITLE
Bug: startDate and endDate not working when they are not in the same year (or maybe, not in the current year)

### ISSUE THREAD

**Issue by khoude24** [benitolopez/hotel-datepicker#62]
```
startDate: "2018-12-25"
endDate: "2019-01-14"

```
![image](https://user-images.githubusercontent.com/4171752/47315466-a7563400-d612-11e8-82d1-cc79c1c8af07.png)
 
All december date are selectable (I cannot go to november with previous arrow (its ok :) )) but date before` 2018-12-25` should not be selectable

If startDate and EndDate are in the same year, everything is allright.

```
startDate: "2019-02-25",
endDate: "2019-02-27",
```

![image](https://user-images.githubusercontent.com/4171752/47315584-0156f980-d613-11e8-9514-32a5c1e72d10.png)

**Comment by benitolopez** [comment]
Right. Fixed in https://github.com/benitolopez/hotel-datepicker/commit/d1f3aada0e4dcc3d53d056a8572863e2bb25c9e6
