### ISSUE TITLE
Wrong second month showing when end of January chosen 

### ISSUE THREAD

**Issue by karlproctor** [benitolopez/hotel-datepicker#64]
You can see this on your example site http://lopezb.com/hoteldatepicker/

If you choose the last days in January, it shows March as the next month instead of February. This goes for 2019 as well as 2020/2021 etc.

![image](https://user-images.githubusercontent.com/47152676/51924580-29f64880-23e5-11e9-979c-a40fa3ba1dfe.png)

**Comment by benitolopez** [comment]
Yes, I see the same problem. But not for 2020 and 2021. So I suspect that it happens because 2019 is a leap year. The plugin calculates 30 days internally to set the next visible month. This is the problem. It happens also if I use 2023 for the year.

I will fix the issue.

**Comment by karlproctor** [comment]
Oh ok! Thanks for the quick reply. 

I noticed that if you choose the last two dates in January for 2020/2021/etc, it shows March too. That's only for January though. If you choose the last two dates for any other month, it shows the next month as expected.

**Comment by benitolopez** [comment]
It should be fixed now (https://github.com/benitolopez/hotel-datepicker/commit/4cf4ad8d88a0220ad9df55de9efc58fb7589a427)
