### ISSUE TITLE
How to automatically set and display a specific number of nights

### ISSUE THREAD

**Issue by DevMA523** [benitolopez/hotel-datepicker#65]
Hi,

How it is possible to automatically define a range of dates when i click only on the start date ?

The range is a constant : 1 week for example.

I need to click on date and automatically, set and display the range.
If some disabled dates are in the range, the range is cancelled.

**Comment by benitolopez** [comment]
Hi,

There's not such option. You can pass a min night value (https://github.com/benitolopez/hotel-datepicker#minnights) but the second date is not selected automatically.

**Comment by DevMA523** [comment]
Thank you. I see i can set a max value too.
I can set the range with the function and i can check the disabled dates.


Can you tell me if you have a function or an event fired when a date is selected ?

**Comment by benitolopez** [comment]
https://github.com/benitolopez/hotel-datepicker#ondayclick
and
https://github.com/benitolopez/hotel-datepicker#onselectrange

**Comment by DevMA523** [comment]
Thank you :) 
Have a nice day
