### ISSUE TITLE
Bug when month-names-short are in lowercase

### ISSUE THREAD

**Issue by Rub3nCT** [benitolopez/hotel-datepicker#66]
When you generate HotelDatepicker using _month-names-short_ in lowercase, the returning month is always January. I first thought it was a Fecha bug, but Fecha works fine so it must be case insensitive.

Just open this test file and check console log.

PS: Not related to this issue, but can you add an usage example of _infoFormat_ to the demo? I don't really understand the usage. THANKS!

[test.zip](https://github.com/benitolopez/hotel-datepicker/files/2848880/test.zip)

**Comment by benitolopez** [comment]
Hi,

Sorry for the late reply. 

This happens also with Fecha when you use lowercase names in `monthNamesShort`. Check the attached file (_test2.html_).
[test2.zip](https://github.com/benitolopez/hotel-datepicker/files/3007211/test2.zip)
