### ISSUE TITLE
Every first day of the week does have the class datepicker__month-day--checkout-enabled

### ISSUE THREAD

**Issue by peda** [benitolopez/hotel-datepicker#68]
I wanted to apply a classic availability calendar styling where departure days are half green and half red. But I did notice that not only possible checkout days do have the class `datepicker__month-day--checkout-enabled` but also every first day of the week in a longer period of unavailability.

**How to reproduce?**
1) Set a whole month (i.e. the month of November) as disabledDates
2) Check which dates do have the `datepicker__month-day--checkout-enabled` - it's not only the 1st November, but also every first day of the week

**Comment by benitolopez** [comment]
It should be fixed in 3.6.8:
https://github.com/benitolopez/hotel-datepicker/commit/611911ebeef4035422b3e16bd25d89c2c4e67715

**Comment by peda** [comment]
Thanks for the amazingly fast fix - it's working perfectly. This ticket can be closed.

**Comment by peda** [comment]
@benitolopez I did some more testing and did notice that we do now have the same issue with every first day of the month. This happens when a hotel has closed (or is fully booked) at the end of month A and the beginning of month B.

**Comment by peda** [comment]
It does only happen if the 1st of a month is the first day of week (i.e. in July)

**Comment by benitolopez** [comment]
It should be fixed now:
https://github.com/benitolopez/hotel-datepicker/commit/0d13dacd4fa3a9b4e629579f704f3059419a6a36

**Comment by peda** [comment]
Thanks, will try it later today

**Comment by peda** [comment]
This is also fixed now - thank you so much
