### ISSUE TITLE
Feature Request: add class to checkin only dates

### ISSUE THREAD

**Issue by peda** [benitolopez/hotel-datepicker#69]
On checkout only dates there is a class `datepicker__month-day--checkout-enabled`

It would be great if on checkin only dates where would be a similar class like `datepicker__month-day--checkin-enabled`

This would allow to also style the checkin-only dates half red/half green like in a classic availability calendar

**Comment by benitolopez** [comment]
Mmm... I'm not sure. We already have a way to style those dates (the `datepicker__month-day--valid` class).

Am I missing something?

**Comment by peda** [comment]
For Check-Out only days I do display the date as half red 

![image](https://user-images.githubusercontent.com/559490/55015522-4c739f00-4fed-11e9-87de-ad2c3884687e.png)

For Check-In only dates I would like to do something similar (6th June) in the following screenshot:

![image](https://user-images.githubusercontent.com/559490/55015537-56959d80-4fed-11e9-82c1-86a64af14254.png)

The problem is that `datepicker__month-day--valid` class is on ALL valid dates and therefore I can't address the first `datepicker__month-day--valid` after a `datepicker__month-day--disabled`. That's why a `datepicker__month-day--checkin-enabled` would be great.

**Comment by benitolopez** [comment]
Something like this should target the first valid day after an invalid date:
```css
.datepicker__month-day--invalid + .datepicker__month-day--valid {}
```

Or you can use this to select the first day after a disabled date:
```css
.datepicker__month-day--disabled + .datepicker__month-day--valid {}
```

I don't like very much the idea to add another class. The main reason is that it will increase the complexity of the code. Handle of those classes is not easy and every time I add a new one the library becomes more difficult to maintain.

**Comment by peda** [comment]
I thought about this solution too but this only works if the first valid date is in the same month as the last disabled date.

I fully understand that this does increase the complexity and I wouldn't have added a feature request for something completely new, but there is a class for checkout only dates and to be consistent there should also be one for checkin only dates.

**Comment by benitolopez** [comment]
Try this:
https://github.com/benitolopez/hotel-datepicker/commit/58a258f5ab7cccf22e9ef136137c84fbf7800a6b

**Comment by peda** [comment]
If the 31st June is unavailable and the July (1st day of month = first column, and first row) and I switch from June to July the 1st July doesn't have this class, but when I switch from August of July it does have it

If the March 31st is available and I switch from March to April (1st day of month = first column, and first row) it doesn't have this class (which is right), but when I do switch from May to April, the 1st April does have this class 

Apart from that it seems to be working - there only is this edge case left where first day of a month is also the first day of a week

**Comment by benitolopez** [comment]
It should be fixed now, I hope :)
https://github.com/benitolopez/hotel-datepicker/commit/d7f76fa2b6c22108b758f3e81f219028735b48a9

**Comment by peda** [comment]
Thanks, that's working now, but unfortuantely there is another bug I discovered now (I'm almost afraid of saying it, because my FR has already caused you so much work)

I initiated the calendar with the following disabled dates:
`disabledDates: ['2020-03-29', '2020-03-28']`

As you can see in the following screenshot it does show the 31st as checkin-only even though the 30th should be the checkin-only date.

![image](https://user-images.githubusercontent.com/559490/55263362-fe6ecd80-5270-11e9-8c5c-f35171aaa3dd.png)

**Comment by benitolopez** [comment]
Please try now.
https://github.com/benitolopez/hotel-datepicker/commit/61f67de5d2981790b42fcef4ff269cb33a3bc0d2

**Comment by peda** [comment]
@benitolopez thank you so much - looks good now :+1: :+1: :+1: :100: :1st_place_medal:

**Comment by benitolopez** [comment]
Finally!
