### ISSUE TITLE
issue with Disable some dates not working.

### ISSUE THREAD

**Issue by omguddu100** [benitolopez/hotel-datepicker#7]
Hi sir,
I try to make disable dates like thats,
1). one ways
         var hdpkr;
        $(document).ready(function () {
            var input = document.getElementById('ppzdate');
            hdpkr = new HotelDatepicker(input, {
              format: 'DD-MM-YYYY',
              autoClose: false,
              disabledDates:  [
                2017-09-27,
                2017-09-23,
                2017-09-26,
                2017-09-28,
                2017-10-01,
                2017-10-11
            ]
            });
            hdpkr.open();
        });
--------------error -------------
![image](https://user-images.githubusercontent.com/16487240/30735893-3a1fff34-9f9e-11e7-85bc-5ec7a5cf786e.png)

2). 2nd ways
because getting disabled dates json
var  disabledDates1= ["2017-09-27","2017-09-23","2017-09-26" ...............................]
 var hdpkr;
        $(document).ready(function () {
             var  disabledDates1= [
                2017-09-27,
                2017-09-23,
                2017-09-26,
                2017-09-28,
                2017-10-01,
                2017-10-11
            ]
            var input = document.getElementById('ppzdate');
            hdpkr = new HotelDatepicker(input, {
              format: 'DD-MM-YYYY',
              autoClose: false,
              disabledDates: disabledDates1,
            });
            hdpkr.open();
        });
-----------error-------------------
getting same error..

Notes: otherwise how to i make some dates is disable.

**Comment by benitolopez** [comment]
You need to pass an array of **strings**. 

```js
hdpkr = new HotelDatepicker(input, {
	format: 'DD-MM-YYYY',
	autoClose: false,
	disabledDates: [
		'2017-09-27',
		'2017-09-23',
		'2017-09-26',
		'2017-09-28',
		'2017-10-01',
		'2017-10-11'
	]
});
```

I will update the readme with an example to avoid any confusion.

**Comment by omguddu100** [comment]
Thanks sir.
I have one doubt also plz help to fixed it.

how to pass the disabledDates  as a dynamic. 
I mean disabledDates[] arguments from outside HotelDatepicker method like.
`
//i want this dates pass like that 
disabledDates: [
                '2017-09-27',
                '2017-09-23',
                '2017-09-26',
                '2017-09-28',
                '2017-10-01',
                '2017-10-11'
            ]
            hdpkr = new HotelDatepicker(input, {
              format: 'DD-MM-YYYY',
              autoClose: false,
              //what i write here..
            });
            hdpkr.open();
          
        });`

**Comment by benitolopez** [comment]
Just use your variable on the disabledDates option:

```js
hdpkr = new HotelDatepicker(input, {
	format: 'DD-MM-YYYY',
	autoClose: false,
	disabledDates: yourDynamicArrayHere
});
```

**Comment by omguddu100** [comment]
thanks for reply

**Comment by omguddu100** [comment]
Hi Sir,
How to get  start-day and end-day dates in two separate in table cell.
please help me to fix this issue 
I want like that
![dats](https://user-images.githubusercontent.com/16487240/30776982-717354aa-a0ce-11e7-94b3-ec133846f841.PNG)
----html----
` <div class="container-fluid">

   <div class="col-md-6">
    <input type="text" id="ppzdate"/ style="visibility: hidden;">
   </div>
   <div class="col-md-6">

     <table class="table">
    <thead>
      <tr>
        <th>Start Dats</th>
        <th>Start Dats</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>DD-MM-YYY</td>
        <td>DD-MM-YYY</td>
        <td><button class="btn btn-success">Add to cart</button></td>
      </tr>
    </tbody>
  </table>
   </div>
            
  
</div>`

-----js-------
` var hdpkr;
        $(document).ready(function () {

         var dynamicdates = [
                '2017-09-27',
                '2017-09-23',
                '2017-09-26',
                '2017-09-28',
                '2017-10-01',
                '2017-10-11'
            ]
             
            var input = document.getElementById('ppzdate');
            hdpkr = new HotelDatepicker(input, {
              format: 'DD-MM-YYYY',
              autoClose: false,
              disabledDates: dynamicdates
              
            });
            hdpkr.open();
            
        });
`

**Comment by benitolopez** [comment]
Hi,

I don't provide support for custom requests. Please issue this rep to report bugs only. Use stackoverflow.com for other questions.

**Comment by Rivaldo35** [comment]
help here bro. how are you?
i want to pass a json array with dates to disable in the datepicker. i did it but once i click one a date, the disabled dates get enabled. can you help?
