### ISSUE TITLE
Class datepicker__month-day--disabled gets removed on month change in selection mode

### ISSUE THREAD

**Issue by peda** [benitolopez/hotel-datepicker#70]
Usually disabled dates do have the following classes: `datepicker__month-day--invalid  datepicker__month-day--disabled`

When you click the start date (and thereby start a selection) and then navigate to another month disabled dates do only have the `datepicker__month-day--invalid` class, but they are missing the `datepicker__month-day--disabled` class - which makes the `X` disappear on disabled dates 

Note: I do have `moveBothMonths: true` set

**Comment by benitolopez** [comment]
Yep. Fixed now:
https://github.com/benitolopez/hotel-datepicker/commit/9d84785579f562cdcd062bf878bddd3b15772d46

**Comment by peda** [comment]
Confirmed that's working now - thank you so much
