### ISSUE TITLE
Change option after selecting first date

### ISSUE THREAD

**Issue by barryvdh** [benitolopez/hotel-datepicker#71]
Is it possible to set options after selecting the first date? The minDate and possible checkout days are depending the season for example, so I would like to set most options depending on the selecting of the start date. Any idea how I would do that? Do I need to reset the view?

**Comment by benitolopez** [comment]
Hi,

This is not possible and unfortunately I don't have a solution to share. It's a great idea but there's nothing in the plugin for that.

I'm closing this issue because it's not a real bug, feel free to make a pull request to implement this feature.

**Comment by barryvdh** [comment]
Okay, thank you for you response. I've tried a few libraries to try different approaches, but the the most promising for now is having a callback for disabling dates. For example https://github.com/dangrossman/daterangepicker runs `isInvalidDate` and `isCustomDate` to enable/disable dates and give custom css classes, instead of determining everything with options.
