### ISSUE TITLE
Disabled dates becoming enabled

### ISSUE THREAD

**Issue by mangao05** [benitolopez/hotel-datepicker#74]
Hello Good Day,

I just find this issue when I'm trying to develop my client booking system,

Whenever I click the first date , **all of the disabled dates becoming active**, I don't know the reason why?

Hope you can help me.

Thanks.

` var input = document.getElementById('dates');
            var datepicker = new HotelDatepicker(input, {
                autoClose : true,
                disabledDates: '{{ json_encode($dates) }}',
                enableCheckout: false, 
                onSelectRange : function(){
                    var nights = datepicker.getNights();
                    var price =  $("#room_price").val();

                    $('#noOfNights').html(nights);

                    var total = price * nights; 
                    $("#cost").val(total);
                    $("#totalCost").html(total);
                }
            });`

**Comment by benitolopez** [comment]
Can I see a live example? Because it doesn't happen in the demo:
http://lopezb.com/hoteldatepicker/

**Comment by mangao05** [comment]
it just happen when the array of  dates came from php, which is Im passing from php to the javascript variable. btw. how to send live example? thank you

**Comment by benitolopez** [comment]
Just send me the URL of this page.
Anyway, I suspect that the disabled dates are not formatted correctly. Check the readme. You need to pass an array of **strings** with that format:
https://github.com/benitolopez/hotel-datepicker#disableddates

**Comment by Rivaldo35** [comment]
they are formatted well..i have the same problem

**Comment by benitolopez** [comment]
Hi,

Please send me the URL of your page where I can see the datepicker in action.

**Comment by mangao05** [comment]
I'll revert my code tomorrow sir. I'll show you what is happening.

**Comment by benitolopez** [comment]
Hi  @mangao05 no problem! The comment was for @Rivaldo35

**Comment by thevirus597** [comment]
Is this problem fixed?

**Comment by thevirus597** [comment]
http://35.193.133.89/vakantiehuis/booking-form.php Here's the link of my website where I have the same issue

**Comment by benitolopez** [comment]
Here I see a datepicker: http://35.193.133.89/vakantiehuis/huis-details.php?id=7

Where did you initialize the datepicker? In what file?

**Comment by thevirus597** [comment]
I initialized it on page load

**Comment by thevirus597** [comment]
I initialized it on the bottom of the file, on page load. Can you check it now please?

**Comment by benitolopez** [comment]
Can you place a console.log of the data variable? I suspect that the dates are not formatted correctly. As I said above (and it is explained in the readme) you need to pass an array of **strings**.

**Comment by thevirus597** [comment]
ther is another issue on http://35.193.133.89/vakantiehuis/huis-details.php?id=7. Can you check on http://35.193.133.89/vakantiehuis/booking-form.php.  Just select "Tapsey" on project, then "Huis1" on vakantiehuis and then the datepicker will get the disabled dates on verblijfdatum

**Comment by benitolopez** [comment]
I don't understand. I see the dates disabled correctly here: http://35.193.133.89/vakantiehuis/booking-form.php

What's the problem?

**Comment by thevirus597** [comment]
The issue is: when you click on a date, all other dates are enabling

**Comment by benitolopez** [comment]
Can you update the library to the last version? I see you're using the v.3.6.6. Last version is 3.6.9: https://github.com/benitolopez/hotel-datepicker/releases

**Comment by thevirus597** [comment]
Still the same thing

**Comment by benitolopez** [comment]
I'm still thinking that the problem is that you're not passing a real array of strings.
Try to change this:

```
disabledDates: response,
```

to this:

```
disabledDates: JSON.parse(response),
```

**Comment by benitolopez** [comment]
Just seen that you have a console.log for the data you're passing to the disabled dates:

```
["2019-08-23","2019-08-24","2019-08-27","2019-08-28","2019-08-29","2019-08-30"]
```

That's not an array of strings. That's a string. That's the problem.

**Comment by thevirus597** [comment]
Thanks mate. It worked!!

**Comment by benitolopez** [comment]
Well, I'm glad you worked it out. 

For everyone else, even future visitors to this issue, I repeat once again: you have to pass an array of strings. Not a single string, nor an array of date objects, nor an object. You can easily check what you're passing with a `console.log()`.
