### ISSUE TITLE
Separate or Update endDate property

### ISSUE THREAD

**Issue by piyush-multiplexer** [benitolopez/hotel-datepicker#75]
How to sepeate to endDate/startDate of check-in and check-out seperately.
new HotelDatepicker(elem, {
              noCheckInDates: checkInDisabled,
              noCheckOutDates: checkOutDisabled,
              disabledDates: dateDisabled,
              endDate: endDate,
            })
At Here how to update endDate on Checkout or Checkin or how to achieve seperate proeprty as noCheckInDates and noCheckOutDates because ii want endDate in both different like checkInEndDate/checkOutEndDate.

**Comment by benitolopez** [comment]
Hi,

Sorry, but I didn't understand your question. There is already a separate `endDate` property available:
https://github.com/benitolopez/hotel-datepicker#enddate

**Comment by piyush-multiplexer** [comment]
Yes there is seperate endDate which works better in single picker, but i want different endDates for checkIn and checkOut pickers. endDate of checkIn should be different than checkout or how can i update it.

**Comment by benitolopez** [comment]
Ha ok now I understand. There's nothing ready for that, this is something you need to implement yourself with some custom JS. The plugin was developed for a single datepicker. I'm closing this issue because it's not a real bug.
