### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by mzengine** [benitolopez/hotel-datepicker#76]
According to your description I should add those two file fecha and hotel-datepicker to my script tag but I have this errors there : **Uncaught SyntaxError: Unexpected token export**
<script type="text/javascript" src="include/theme/elite/javaScript/fecha.js"></script>
<script type="text/javascript" src="include/theme/elite/javaScript/hotel-datepicker.js"></script>

So, I change the type into module like this
<script type="module" src="include/theme/elite/javaScript/fecha.js"></script>
<script type="module" src="include/theme/elite/javaScript/hotel-datepicker.js"></script>

That error Uncaught SyntaxError: Unexpected token export is gone but I have another error 
called: **Uncaught ReferenceError: HotelDatepicker is not defined**

So soome how it does not load the class at all. In your description how to use this says only download the files and add them to your script but It DOESN'T WORK according to your description.

Can you tell me what are the steps to get it work?
Thanks.

**Comment by benitolopez** [comment]
Hi,

Yes, it works and you need to include the files in that way:

```
<script src="/path/to/fecha.js"></script>
<script src="/path/to/hotel-datepicker.min.js"></script>
```

You don't need the type "module" at all. So be sure that your paths are correct. 

If it doesn't work, please share the URL of your page here.

**Comment by mzengine** [comment]
Hi,
Sorry but i did include my path as you can see : 
**<script type="module" src="include/theme/elite/javaScript/fecha.js"></script>**
without that module it won't load and is coming back with error.
It's on my localhost so I can't share the path. Sorry but this date picker doesn't work at all.
Like I said there are errors that can't load and after include "module" its coming back with different errors.

**Comment by benitolopez** [comment]
Hi,

The datepicker works. It's not working on your website, this is a different story.

Again: can you share the URL of your page here? I need the URL, otherwise it is impossible to help you.

**Comment by mzengine** [comment]
http://php-booking.localdomain.ee/

I don't think you can see this as its on localhost

**Comment by benitolopez** [comment]
Ok just seen the edit. You're on localhost.

Try this:
1. Include the scripts without "module" (don't use anything, like I wrote above)
2. Use an absolute path, like "http://localhost/include/theme/elite/javaScript/fecha.js"
3. To be sure that the path is correct, open a new window of your browser and visit the same path (http://localhost/include/theme/elite/javaScript/fecha.js). If you see the code, it means that the path is correct. If you see an error, the path is not correct and that's your problem.

**Comment by mzengine** [comment]
the path is correct because when I click on the link src it will open a window and show me the whole file.

**Comment by mzengine** [comment]
if you read that error that I have post
you realize that jquery can't load this so there is something wrong with the installation the way you said it needs to be install. I think there missing files that you forgot to mentioned plus how to use in the file.

**Comment by benitolopez** [comment]
No, absolutely. There is no missing information. This plugin has 3 years and this is the first time that I see this problem. Just check the issues if you don't trust me. 

There's probably an error on your installation. So please stop to insinuate that I'm not reading your comments and all of that. Because I'm here during my work break trying to help you.

Anyway, just uploaded a test here: http://lopezb.com/hoteldatepicker/test/

Everything works correctly. With jQuery 3.4.1 and following the installation instructions. Nothing else. Check the source code.

**Comment by benitolopez** [comment]
Please make a public accessible installation of your setup. When done, share the URL here.

**Comment by mzengine** [comment]
|  
-- | --
  | <!DOCTYPE html>
  | <html lang="en" dir="ltr">
  |  
  | <head>
  | 
  |  
  | 
  | <meta charset="utf-8">
  | <title>Elite Island Resort - EIR</title>
  | <meta name="keywords" content="Elite Island Resort" />
  | <meta name="description" content="none" />
  | <meta name="language" content="en-gb" />
  | <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  | <meta name="HandheldFriendly" content="True" />
  | <link rel="apple-touch-icon" sizes="180x180" href="/include/theme/elite/images/apple-touch-icon.png">
  | <link rel="icon" type="image/png" sizes="32x32" href="/include/theme/elite/images/favicon-32x32.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/include/theme/elite/images/favicon-16x16.png">
  | <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/theme-default.min.css" rel="stylesheet" type="text/css" />
  | <link rel="stylesheet" href="/include/theme/elite/CSS/style.css">
  | <link rel="stylesheet" href="/include/theme/elite/CSS/devstylesheet.css">
  | <link rel="stylesheet" href="/include/theme/elite/CSS/hotel-datepicker.css">
  | <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  | <script src="/include/theme/elite/javaScript/vanilla.js"></script>
  | </head>
  |  
  | <body>
  | 
  |  
  | 
  | <header id="header">
  | <div class="logo">
  | <a href="index.php"><img src="/include/theme/elite/images/eir-logo.svg" alt="Elite Island Resorts"></a>
  | </div>
  | <div class="">
  | <span>To book call: </span>
  | <span class="">01245 459 906</span><br>
  | <a href="mailto:res@eliteislandresorts.co.uk">res@eliteislandresorts.co.uk</a>
  | </div>
  | </header><main>
  | <section>
  | <h1>Find Your Perfect Caribbean Resort</h1>
  | <form id="form-search" action="index.php?page=result" method="post">
  | <div class="form-group">
  | <label for="search">Search</label>
  | <select name="search" id="search" data-validation="required">
  | <option value="0">All Hotels</option>
  | <option value='21'>Galley Bay Resort & Spa</option><option value='204'>Hammock Cove Resort & Spa</option><option value='17'>Palm Island Resort</option><option value='181'>Pineapple Beach Club</option><option value='19'>St James's Club & Villas, Antigua</option><option value='73'>St James's Club Morgan Bay Saint Lucia</option><option value='78'>The Club Barbados Resort & Spa</option><option value='20'>The Verandah Resort & Spa</option>
  | </select>
  | </div>
  | <div class="form-group">
  | <label for="checkIn">Check-In</label>
  | <input type="text" id="input-id" name="checkIn" class="checkIn" data-validation="date">
  | <img src="/include/theme/elite/images/calendar.png" alt="calendar">
  | </div>
  | <div class="form-group">
  | <label for="nights">Nights</label>
  | <select name="nights" id="nights">
  | <option value="1">1</option>
  | <option value="2">2</option>
  | <option value="3">3</option>
  | <option value="4">4</option>
  | <option value="5">5</option>
  | <option value="6">6</option>
  | <option value="7" selected>7</option>
  | <option value="8">8</option>
  | <option value="9">9</option>
  | <option value="10">10</option>
  | <option value="11">11</option>
  | <option value="12">12</option>
  | <option value="13">13</option>
  | <option value="14">14</option>
  | <option value="15">15</option>
  | <option value="16">16</option>
  | <option value="17">17</option>
  | <option value="18">18</option>
  | <option value="19">19</option>
  | <option value="20">20</option>
  | <option value="21">21</option>
  | </select>
  | </div>
  | <div class="form-group">
  | <label for="checkOut">Check-Out</label>
  | <input type="text" name="checkOut" class="checkOut">
  | <img src="/include/theme/elite/images/calendar.png" alt="calendar">
  | </div>
  | <div class="form-group">
  | <label for="rooms">Rooms</label>
  | <select name="rooms" id="rooms">
  | <option value="1" selected>1</option>
  | <option value="2">2</option>
  | <option value="3">3</option>
  | <option value="4">4</option>
  | </select>
  | </div>
  | <div class="form-group">
  | <label for="adults">Adults</label>
  | <input type="text" name="adults" id="adults" data-validation="required">
  | </div>
  | <input type="submit" name="find" id="find" value="Find results">
  | </form>
  | </section>
  | </main><footer id="footer">
  | <article class="">
  | <form action="https://resort-marketing.us15.list-manage.com/subscribe/post?u=53f3320ed50e3af449a59fd25&amp;id=ab23ceba7c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
  | <div id="mc_embed_signup_scroll">
  | <label for="mce-EMAIL">Subscribe to our mailing list</label>
  | <input type="email" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email Address" data-validation="email" />
  | 
  | <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_53f3320ed50e3af449a59fd25_ab23ceba7c" tabindex="-1" value="" /></div>
  | <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" /></div>
  | </div>
  | </form>
  | </article>
  | <article class="">
  | <ul class="">
  | <li class=""><a href="https://eliteislandholidays.com/cookie-policy/">Cookie Policy</a></li>
  | <li class=""><a href="https://eliteislandholidays.com/privacy-policy/">Privacy Policy</a></li>
  | <li class=""><a href="https://eliteislandholidays.com/terms-and-conditions/">Terms and Conditions</a></li>
  | </ul>
  | </article>
  | </footer>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
  | <script src="include/theme/elite/javaScript/fecha.js"></script>
  | <script src="include/theme/elite/javaScript/hotel-datepicker.js"></script>
  | <script>
  | var input = document.getElementById('input-id');
  | var datepicker = new HotelDatepicker(input);
  | </script>
  | <script src="include/theme/elite/javaScript/main.js"></script>
  |  
  | </body>
  |  
  | </html>

**Comment by mzengine** [comment]
`

  |  
-- | --
  | <!DOCTYPE html>
  | <html lang="en" dir="ltr">
  |  
  | <head>
  | 
  |  
  | 
  | <meta charset="utf-8">
  | <title>Elite Island Resort - EIR</title>
  | <meta name="keywords" content="Elite Island Resort" />
  | <meta name="description" content="none" />
  | <meta name="language" content="en-gb" />
  | <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  | <meta name="HandheldFriendly" content="True" />
  | <link rel="apple-touch-icon" sizes="180x180" href="/include/theme/elite/images/apple-touch-icon.png">
  | <link rel="icon" type="image/png" sizes="32x32" href="/include/theme/elite/images/favicon-32x32.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/include/theme/elite/images/favicon-16x16.png">
  | <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/theme-default.min.css" rel="stylesheet" type="text/css" />
  | <link rel="stylesheet" href="/include/theme/elite/CSS/style.css">
  | <link rel="stylesheet" href="/include/theme/elite/CSS/devstylesheet.css">
  | <link rel="stylesheet" href="/include/theme/elite/CSS/hotel-datepicker.css">
  | <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  | <script src="/include/theme/elite/javaScript/vanilla.js"></script>
  | </head>
  |  
  | <body>
  | 
  |  
  | 
  | <header id="header">
  | <div class="logo">
  | <a href="index.php"><img src="/include/theme/elite/images/eir-logo.svg" alt="Elite Island Resorts"></a>
  | </div>
  | <div class="">
  | <span>To book call: </span>
  | <span class="">01245 459 906</span><br>
  | <a href="mailto:res@eliteislandresorts.co.uk">res@eliteislandresorts.co.uk</a>
  | </div>
  | </header><main>
  | <section>
  | <h1>Find Your Perfect Caribbean Resort</h1>
  | <form id="form-search" action="index.php?page=result" method="post">
  | <div class="form-group">
  | <label for="search">Search</label>
  | <select name="search" id="search" data-validation="required">
  | <option value="0">All Hotels</option>
  | <option value='21'>Galley Bay Resort & Spa</option><option value='204'>Hammock Cove Resort & Spa</option><option value='17'>Palm Island Resort</option><option value='181'>Pineapple Beach Club</option><option value='19'>St James's Club & Villas, Antigua</option><option value='73'>St James's Club Morgan Bay Saint Lucia</option><option value='78'>The Club Barbados Resort & Spa</option><option value='20'>The Verandah Resort & Spa</option>
  | </select>
  | </div>
  | <div class="form-group">
  | <label for="checkIn">Check-In</label>
  | <input type="text" id="input-id" name="checkIn" class="checkIn" data-validation="date">
  | <img src="/include/theme/elite/images/calendar.png" alt="calendar">
  | </div>
  | <div class="form-group">
  | <label for="nights">Nights</label>
  | <select name="nights" id="nights">
  | <option value="1">1</option>
  | <option value="2">2</option>
  | <option value="3">3</option>
  | <option value="4">4</option>
  | <option value="5">5</option>
  | <option value="6">6</option>
  | <option value="7" selected>7</option>
  | <option value="8">8</option>
  | <option value="9">9</option>
  | <option value="10">10</option>
  | <option value="11">11</option>
  | <option value="12">12</option>
  | <option value="13">13</option>
  | <option value="14">14</option>
  | <option value="15">15</option>
  | <option value="16">16</option>
  | <option value="17">17</option>
  | <option value="18">18</option>
  | <option value="19">19</option>
  | <option value="20">20</option>
  | <option value="21">21</option>
  | </select>
  | </div>
  | <div class="form-group">
  | <label for="checkOut">Check-Out</label>
  | <input type="text" name="checkOut" class="checkOut">
  | <img src="/include/theme/elite/images/calendar.png" alt="calendar">
  | </div>
  | <div class="form-group">
  | <label for="rooms">Rooms</label>
  | <select name="rooms" id="rooms">
  | <option value="1" selected>1</option>
  | <option value="2">2</option>
  | <option value="3">3</option>
  | <option value="4">4</option>
  | </select>
  | </div>
  | <div class="form-group">
  | <label for="adults">Adults</label>
  | <input type="text" name="adults" id="adults" data-validation="required">
  | </div>
  | <input type="submit" name="find" id="find" value="Find results">
  | </form>
  | </section>
  | </main><footer id="footer">
  | <article class="">
  | <form action="https://resort-marketing.us15.list-manage.com/subscribe/post?u=53f3320ed50e3af449a59fd25&amp;id=ab23ceba7c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
  | <div id="mc_embed_signup_scroll">
  | <label for="mce-EMAIL">Subscribe to our mailing list</label>
  | <input type="email" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email Address" data-validation="email" />
  | 
  | <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_53f3320ed50e3af449a59fd25_ab23ceba7c" tabindex="-1" value="" /></div>
  | <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" /></div>
  | </div>
  | </form>
  | </article>
  | <article class="">
  | <ul class="">
  | <li class=""><a href="https://eliteislandholidays.com/cookie-policy/">Cookie Policy</a></li>
  | <li class=""><a href="https://eliteislandholidays.com/privacy-policy/">Privacy Policy</a></li>
  | <li class=""><a href="https://eliteislandholidays.com/terms-and-conditions/">Terms and Conditions</a></li>
  | </ul>
  | </article>
  | </footer>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
  | <script src="include/theme/elite/javaScript/fecha.js"></script>
  | <script src="include/theme/elite/javaScript/hotel-datepicker.js"></script>
  | <script>
  | var input = document.getElementById('input-id');
  | var datepicker = new HotelDatepicker(input);
  | </script>
  | <script src="include/theme/elite/javaScript/main.js"></script>
  |  
  | </body>
  |  
  | </html>

`

**Comment by mzengine** [comment]
no need to get angry.
Your files are wrong and not explain how to use it as I inspect your file that you are using in your test start like this: 

**/*! hotel-datepicker 3.6.9 - Copyright 2019 Benito Lopez (http://lopezb.com) - https://github.com/benitolopez/hotel-datepicker - MIT */
var HotelDatepicker = function() {
	"use strict";
	var t = 0,
		e = function t(e, s) {
			this._boundedEventHandlers = {}, this.id = t.getNewId();
			var a = s || {};**

Now the file that are here in the src start like this:

**'use strict';
/* global fecha, DocumentTouch */
/* eslint-disable no-multi-assign */
let idCounter = 0;

export default class HotelDatepicker {
	constructor(input, options) {
		this._boundedEventHandlers = {};
		this.id = HotelDatepicker.getNewId();

        // Set default values
		const opts = options || {};
**

you see the difference? When I have used those files that you are using in your test then now it works but when I used yours here in git then it doesn't work work. you try with those files that you have here and you will see the difference. 

Thanks anyway for your time and now it works as I have use your files that you are using in your test.
Regards 

PS: maybe you should have look on your files on src/js/hotel-datepicker.js

**Comment by benitolopez** [comment]
Well of course, the **src** folder is the development one. You obviously need to use the files included in the **dist** folder. Like in other libraries. This is a common practice.

Anyway, the instructions say that you need to include this file:

```
<script src="/path/to/hotel-datepicker.min.js"></script>
```

There is not any `hotel-datepicker.min.js` file in the **src** folder. It's in the **dist** folder.

PS: The files on **src** are for development purposes as I said. Those are compiled and they generate the dist folder. So everything is ok there.
