### ISSUE TITLE
Wordpress: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by dmnktoe** [benitolopez/hotel-datepicker#78]
After I successfully set up the plugin on my local machine in pure HTML & Javascript I got everything working. After I implemented all functions in a custom WordPress plugin, I get the following error:

`Uncaught TypeError: Cannot read property 'parentElement' of null
    at HotelDatepicker.init (hotel-datepicker.js?ver=5.1.3:196)
    at new HotelDatepicker (hotel-datepicker.js?ver=5.1.3:70)
    at main.js?ver=5.1.3:33
    at main.js?ver=5.1.3:76`

I already put the initialization of the `Hotel Datepicker` into a `document.ready` like function.

Project URL: http://alpensonne.printmedia-agentur.de/de/startseite/

**Comment by benitolopez** [comment]
I see that it is working now. Did you solve the problem?
