### ISSUE TITLE
Is it possible to split the entry field for entry and exit?

### ISSUE THREAD

**Issue by hebriels** [benitolopez/hotel-datepicker#79]
Hey. There is an example of the implementation of this calendar. Can you make one? And how much does it cost? [https://sochi.sutochno.com/703553](url)

**Comment by benitolopez** [comment]
Hi,

Unfortunately, this datepicker is meant for a single date range picker. So this is something you need to implement yourself.

I'm unable to help you and I'm not available for paid jobs.

Best,
Benito
