### ISSUE TITLE
Pre-Determined date range

### ISSUE THREAD

**Issue by riseoflex88** [benitolopez/hotel-datepicker#8]
Hi, 

This looks awesome and I'm really hoping I can use it on a project I'm working on however it has slightly different requirements. 

Essentially, instead of hotel booking, it's for trip booking. The requirements are almost identical except instead of allowing the user to choose the date range, it's already pre-determined to 'x days'.

Is there a workaround (or supported functionality) to change the behaviour so that when a user clicks on the first date, the second date is automatically selected (highlighting the days inbetween)?

**Comment by benitolopez** [comment]
Hi,

There is already an option that allows you to set a minimum nights stay (check the demo). But it doesn't highlight the 7 nights until you hover on the desired checkout date.

Unfortunately there's not any workaround to integrate such functionality. You need to modify the plugin.

**Comment by riseoflex88** [comment]
Ok thanks for the (lightening fast) response 👍
