### ISSUE TITLE
Calendar alignment

### ISSUE THREAD

**Issue by nscnm87** [benitolopez/hotel-datepicker#80]
Hi,
I have an issue with the calendar, my form is on the right side of the page and when I click on it the second month of the calendar is partially out of the page.

Is there a way to select the alignment?

Thank you in advance,
Fabio

![Screenshot_2020-01-27 CORTIJO FUENTE MARCHAL - Turismo rural en la Serrania de Ronda(1)](https://user-images.githubusercontent.com/3383995/73171063-297bb500-4100-11ea-8949-f55da5bfed35.png)

**Comment by benitolopez** [comment]
Hi,

This is a CSS issue related to your custom integration, not a bug. Just modify your CSS. 

As a reference, the example CSS included shows the second month after a window breakpoint (when the window is at 480px and above): https://github.com/benitolopez/hotel-datepicker/blob/master/src/sass/_base.scss#L55

Just modify that.
