### ISSUE TITLE
not working on 2 elements on click event

### ISSUE THREAD

**Issue by huzoorbux** [benitolopez/hotel-datepicker#81]
Only work when #in clicked first if I click #out first it doesn't show calender on any button click

```
(function() {
            
            var $btnin = $('#in');
            $btnin.children("div").children("h2.date").html(fecha.format(new Date(), 'DD'));
            $btnin.children("div").children("span.month").html(fecha.format(new Date(), 'MMM'));
            
            
            var $btnout = $('#out');
            var ms = new Date().getTime() + (86400000*3);
            $btnout.children("div").children("h2.date").html(fecha.format(new Date(ms), 'DD'));
            $btnout.children("div").children("span.month").html(fecha.format(new Date(ms), 'MMM'));



            var dateRange = new HotelDatepicker(document.getElementById('datein'), {
                minNights: 7,
                showTopbar: false,
                format: 'YYYY-MM-DD',
				onSelectRange: function() {
                    $btnin.children("div").children("h2.date").html(fecha.format(this.start, 'DD'));
                    $btnin.children("div").children("span.month").html(fecha.format(this.start, 'MMM'));

                    $btnout.children("div").children("h2.date").html(fecha.format(this.end, 'DD'));
                    $btnout.children("div").children("span.month").html(fecha.format(this.end, 'MMM'));
				}
            });

            $("#in").click(function(){
                dateRange.open();
            });
            $("#out").click(function(){
                dateRange.open();
            });
		})();
```

**Comment by benitolopez** [comment]
Hi,

Please check the console tab on your browser. I don't think that this issue is related to the datepicker, but to your custom code.

What happens if you don't pass a function to the `onSelectRange` option?

```
var dateRange = new HotelDatepicker(document.getElementById('datein'), {
                minNights: 7,
                showTopbar: false,
                format: 'YYYY-MM-DD'
});
```

Probably the error is somewhere in these two lines:

```
$btnout.children("div").children("h2.date").html(fecha.format(this.end, 'DD'));
$btnout.children("div").children("span.month").html(fecha.format(this.end, 'MMM'));
```

**Comment by huzoorbux** [comment]
There is no error in the console.

I have fixed it by adding my input below both click options.

its working on below form
```
<form action="" method="GET">
        <div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
            <div class="check-in text-center dm" data-val="in" id="in">
                <div class="">check-in</div>
                <div class="col-xs-6">
                    <h2 class="date"></h2>
                </div>
                <div class="col-xs-6">
                    <span class="month"></span><br /><i class="fa fa-angle-down"></i>
                </div>   
            </div>
        </div>
        <div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
            <div class="check-out text-center sep dm" data-val="out" id="out">
                <div class="">check-out</div>
                <div class="col-xs-6">
                    <h2 class="date"></h2>
                </div>
                <div class="col-xs-6">
                        <span class="month"></span><br /><i class="fa fa-angle-down"></i>
                </div>           
            </div>
        </div>
        <input type="hidden" id="datein">
        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
            <button type="submit" class="btn btn-primary btn-block c_button">Check Availability</button>
        </div>
    </form>
```

not working on this form 

<form action="" method="GET">
        <div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
            <div class="check-in text-center dm" data-val="in" id="in">
                <div class="">check-in</div>
                <div class="col-xs-6">
                    <h2 class="date"></h2>
                </div>
                <div class="col-xs-6">
                    <span class="month"></span><br /><i class="fa fa-angle-down"></i>
                </div>   
 <input type="hidden" id="datein">
            </div>
        </div>
        <div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
            <div class="check-out text-center sep dm" data-val="out" id="out">
                <div class="">check-out</div>
                <div class="col-xs-6">
                    <h2 class="date"></h2>
                </div>
                <div class="col-xs-6">
                        <span class="month"></span><br /><i class="fa fa-angle-down"></i>
                </div>           
            </div>
        </div>
        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
            <button type="submit" class="btn btn-primary btn-block c_button">Check Availability</button>
        </div>
    </form>

**Comment by benitolopez** [comment]
Ok found the problem. Tha datepicker autocloses if the event target (the node where you click) is not contained in the datepicker parent: https://github.com/benitolopez/hotel-datepicker/blob/master/src/js/hotel-datepicker.js#L657

So in your case, when you click on h2.date (second date) it autocloses. Because that div is not inside the datepicker parent (the div #in).

Your last code works because the parent is the form, which is the parent of both divs h2.date.

**Comment by huzoorbux** [comment]
@benitolopez Got it Thanks :-)
