### ISSUE TITLE
Select dates in the past

### ISSUE THREAD

**Issue by tkima** [benitolopez/hotel-datepicker#82]
Is there a way to also select dates in the past? 
I did fiddle around with the "createMonthDomString(_date) {" function and I can now select a date in the past but not the checkout date in the past.

Other option what i was thinking is to manipulate the "today" date to a past date but i can't find it where it is set. 

Someone a good tip to get the result?

**Comment by benitolopez** [comment]
Hi,

Sorry for the late reply. Just use the `startDate` option:

```js
var hdpkr = new HotelDatepicker(document.getElementById('input-id'), {
    startDate: new Date(2010,01,01)
});
```
