### ISSUE TITLE
3rd of month

### ISSUE THREAD

**Issue by mar7t1n** [benitolopez/hotel-datepicker#84]
There is a bug for "3rd" of each month where date format is "Do" e.g. 1st, 2nd, 3rd. The replace is missing **rd** from th|nd|st and should be (th|nd|**rd**|st). 

However I'm not sure if the replace is necessary at all because fecha at v2.3.3 understands the Do format and correctly converts a date without the need for the replace at all. Thus would suggest removing entirling the lines which do the match(/Do/) from these 2 functions:

- checkAndSetDefaultValue()
- getNights()

**Comment by benitolopez** [comment]
Yep, fixed: https://github.com/benitolopez/hotel-datepicker/commit/cace4fbb80a83d93c43b82c02128d392266263ea
