### ISSUE TITLE
fecha strict branch need to use

### ISSUE THREAD

**Issue by tgely** [benitolopez/hotel-datepicker#85]
Hi,

I think the latest fecha branch is not compatible so I used the strict branch

**Comment by marttiku** [comment]
Fecha 3.0.3 works - https://github.com/taylorhakes/fecha/tree/3.0.3
Fecha has a breaking change on how it handles i18n

**Comment by benitolopez** [comment]
A new version is out (4.0.0) that requires Fecha 4.0.0 and above.

**Comment by tgely** [comment]
Thank you guys!
Perfect!
