### ISSUE TITLE
BUG: Can't activate days before-disabled-date

### ISSUE THREAD

**Issue by gitsnippets** [benitolopez/hotel-datepicker#86]
Lets have a look at the July 2020, minNights are 5, checkIn is true, the 22nd of July is disabled.
The 5 days before the 22nd are disabled for checkin, that's perfect.
So, when I click on the 10th of July, just the 22nd and the 21st are available for checkout. But the 18th, 19th and 20th should be also.
Has someone any solution?
.before-disabled-date

**Comment by benitolopez** [comment]
Hi,

I just created a quick test and all seems correct. You can see it here:
http://lopezb.com/test-issue-86/

Please share the URL of your page, otherwise, it is difficult to help you.

**Comment by gitsnippets** [comment]
Hey thx for your fast reply.
My code is actually just local. But I had a look at your url, you send me. You forgot the option enableCheckOut:true
On the other hand in your test-code, it is possible to click checkin on 20th of july. That should be not possible, right?

My issue is of course very special and just for ux. You did a great job.

Regards from Germany
Björn

**Comment by gitsnippets** [comment]
Perhaps it helps, when I send you my options-code:
var droptions = {
  format: 'DD.MM.YYYY',
  minNights: 1,
  disabledDaysOfWeek: [], //'Montag'
  startDate: fecha.format(new Date(), 'DD.MM.YYYY'),
  selectForward: true,
  disabledDates: [],
  autoClose: false,
noCheckInDates: ['2020-06-18'],
noCheckOutDates: ['2020-06-16'],
enableCheckout: true,
i18n: {
  selected: 'gewählt:',
  night: 'Nacht',
  nights: 'Nächte',
  button: 'schliessen',
  'checkin-disabled': 'Check-in nicht möglich',
  'checkout-disabled': 'Check-out nicht möglich',
  'day-names-short': ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  'day-names': ['Sonntag','Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
  'month-names-short': ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
  'month-names': ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
  'error-more': 'Der Datumsbereich darf nicht mehr als 1 Nacht betragen.',
  'error-more-plural': 'Der Datumsbereich darf nicht mehr als %d Nächte betragen.',
  'error-less': 'Der Datumsbereich darf nicht weniger als 1 Nacht betragen.',
  'error-less-plural': 'Der Datumsbereich darf nicht weniger als %d Nächte haben',
  'info-more': 'Bitte wählen Sie einen Datumsbereich mit mindestens einer Nacht',
  'info-more-plural': 'Bitte wählen Sie einen Datumsbereich größer als %d Nächte',
  'info-range': 'Bitte wählen Sie ein Datum zwischen %d und %d',
  'info-default': 'Bitte wählen Sie einen Datumsbereich'
}
}
$.each($('input[type=date].drpicker'), function(){
  if ($(this).data('options') == true){
    droptions.minNights = $(this).data('minnights')??droptions.minNights;
    droptions.startDate = $(this).data('startdate')??droptions.startDate;
    droptions.enableCheckout = $(this).data('enablecheckout')??droptions.enableCheckout;
    if ($(this).data('disableddaysofweek') != undefined){
      droptions.disabledDaysOfWeek = $(this).data('disableddaysofweek').split(',');
    }
    if ($(this).data('disableddates') != undefined){
      droptions.disabledDates = $(this).data('disableddates').split(',');
    }
    if ($(this).data('nocheckindates') != undefined){
      droptions.noCheckInDates = $(this).data('nocheckindates').split(',');
    }
    if ($(this).data('nocheckoutdates') != undefined){
      droptions.noCheckOutDates = $(this).data('nocheckoutdates').split(',');
    }
  }
  var datepicker = new HotelDatepicker(document.getElementById($(this).attr('id')),droptions);
});

**Comment by benitolopez** [comment]
I updated the page, it works.

PS. Yeah, maybe you shouldn't be able to click on July 20th. But the plugin allows you to select the range in both directions. So you have to be able to click it. If you use the "selectForward" option you could avoid it (in any case it doesn't allow you to select a date range). I will think about it in the future, but at the moment it doesn't have priority.

**Comment by benitolopez** [comment]
Updated the test again: now it contains your same configuration on the second input.

**Comment by benitolopez** [comment]
Anyway yes, when "selectForward" is active you shouldn't be able to click on the 20th of July. As soon as I have some time I will send a fix, in the meantime you can disable the option "selectForward".

**Comment by gitsnippets** [comment]
Thx for support, I’ll check in the next days.
