### ISSUE TITLE
Enabled dates

### ISSUE THREAD

**Issue by riseoflex88** [benitolopez/hotel-datepicker#9]
Is it / would it be possible to provide a whitelist of dates rather than the blacklist of dates for the disabled dates. 

Ideally the availability would be in the reverse to what's currently formatted, by inputting the available dates

**Comment by benitolopez** [comment]
Unfortunately not. Such functionality would require a big refactoring of the code and it doesn't make sense for the nature of this project. The project was developed for an hotel datepicker specifically, with the intent of maintain the features simple as much as possible.
