### ISSUE TITLE
How disable date range?

### ISSUE THREAD

**Issue by logan-19** [benitolopez/hotel-datepicker#91]
Hi, how disable date range?
If I have selected a date range for the hotel (eg. from 2021-01-01 to 2021-01-10 and from 2021-01-24 to 2021-01-30), how can I disable these ranges, this is the most important for the calendar.

**Comment by benitolopez** [comment]
The plugin accepts only an array of strings. ie. an array of single dates, not a range. But you can easily create a range with Javascript and pass the result to [disabledDates](https://github.com/benitolopez/hotel-datepicker#disableddates).

How to create the range is up to you.
