### ISSUE TITLE
Jalali Calendar

### ISSUE THREAD

**Issue by MR-Mostafa** [benitolopez/hotel-datepicker#93]
Hello
Is any way to your datepicker support jalali calendar (Persian Calendar)?
For logic difference between these dates(jalali & gregorian) you can use: [Persian Date](http://babakhani.github.io/PersianWebToolkit/doc/persian-date/) OR [jalaali-js](https://github.com/jalaali/jalaali-js)
Thanks

**Comment by benitolopez** [comment]
Hello,

Unfortunately, I'm not familiar with other calendars so I don't think I can work on it, also considering the little time I have to dedicate to the project. Sorry.

Anyway, you can fork the project and implement it yourself.

Best,
Benito
