### ISSUE TITLE
How to use in a specific way.

### ISSUE THREAD

**Issue by mits87** [benitolopez/hotel-datepicker#94]
Hello, 

First of all congrats for the nice script!
I have some questions because I'm not sure how can I achieve some behaviours.

1. I would like to embed only a single calendar without input. Is is possible?
2. Is it possible to mark the date diagonally? I would like to show for the user selected nights not days. 
3. Is it possible to select many date ranges inside one calendar? 
4. Is it possible to dispatch some callback after when I finish selecting the range?

Thank you in advance for the reply.
Best

**Comment by benitolopez** [comment]
Hello,

All the features are visible in the demo and explained in the readme. So if you can't find something, it means that there's not an option in the library for that.

Anyway:

1. The input is mandatory, you can find a way to hide it by CSS.
2. This is just CSS. The CSS included in the library is just an example. You can customize it.
3. No, only one range.
4. Yes, https://github.com/benitolopez/hotel-datepicker#onselectrange
