### ISSUE TITLE
open() trigger isn't work well

### ISSUE THREAD

**Issue by uyesercan** [benitolopez/hotel-datepicker#95]
Hi @benitolopez thanks for very useful hotel-datepicker. I have a problem with the open() trigger. Here is my code:

< button type="submit" id="opendatepicker" class="btn btn-warning btn-lg btn-block">OPEN< /button >

$( "#opendatepicker" ).click(function() {
	datepicker.open();
});

The problem is calendar doesn't show when click button. Because, style is stay like this, not delete :

![resim](https://user-images.githubusercontent.com/8599309/108815520-a9a37100-75c5-11eb-8ad2-181dfe157aff.png)

**Comment by uyesercan** [comment]
By the way if i set, 
preventContainerClose: true,
there is no problem.

**Comment by benitolopez** [comment]
Hello,

Can you share a public accessible URL with this datepicker?

Also, in the demo there's an example with a button that opens the datepicker. Please try to use the same logic/markup/js in your datepicker. 

I suspect that it is just an initialization problem or just the datepicker in the wrong div. Check the demo. If the issue persists, please share the URL. But first, please check your markup and adapt it if needed.

**Comment by uyesercan** [comment]
I will be add link but need few days.

Before open this issue, I was followed the demo process exactly. Same problem...

Yes it's look like to me too initialization problem.

**Comment by uyesercan** [comment]
Here is my page. If I delete the preventContainerClose: true option, the problem appears. But now it works very well. 

By the way I want to show the calendar for 6 months in a external modal...

https://www.islamlarvillas.com/kiralik-villalar/villa-huma-1/

![resim](https://user-images.githubusercontent.com/8599309/110333954-45f05d80-8033-11eb-9d74-bba25a18af48.png)

**Comment by benitolopez** [comment]
Hello,

As suspected, your code is not the same as the demo. Because in the demo the datepicker input and the button are inside the same div. On your website, the button is in another container. 

So yes, you need to use `preventContainerClose` in this case to prevent the automatic closing.

Regarding your other question, unfortunately, I'm not able to help you with custom code or integrations. This repo is for reporting bugs only.

**Comment by uyesercan** [comment]
@benitolopez, thanks for the explanation. Buona giornata!
