### ISSUE TITLE
Can´t find fecha.min.js

### ISSUE THREAD

**Issue by ZuluSP** [benitolopez/hotel-datepicker#96]
Hey there! im a programmer student doing a full hotel proyect.

I´ve read your repositorie and seems really cool, so i wanted to implement that datepicker to my project.

The problem is that i cannot find the file "Fecha.min.js", on the "read-me" file you recommend me to implement that on the script, but i couldn´t find it.

¿Is that file necessary?

Thanks

**Comment by benitolopez** [comment]
Hello,

You're right, the instructions on how to install Fecha could be better. I will update the readme as soon as possible. 

Anyway, you can download the last release of Fecha here:
https://github.com/taylorhakes/fecha/releases

Benito

**Comment by benitolopez** [comment]
https://github.com/benitolopez/hotel-datepicker/commit/26263f3c7a3c1c02732422484a78ea494ec9eeec
