### ISSUE TITLE
Get Year when format date is hiding it

### ISSUE THREAD

**Issue by andreas-pa** [benitolopez/hotel-datepicker#97]
Hello and sorry in advanced if the question is a little bit silly.

In the options I am having this format : 

`format: 'D MMM'`

When I am getting the selected values (for example with `getValue()`) the returned value having the same format. 

Example : 

I am selecting 9 Mar (from 2021) until 9 Mar (from 2022)  , this is 365 days. 

`getValue()` will return -> 9 Mar - 9 Mar 

Is there any way to get the full date including Year so I can manipulate then the dates?

Thank you very much in advanced

**Comment by benitolopez** [comment]
Hello,

This plugin wasn't meant to be used without a year. 

Anyway, you can get the start and end values with `yourDatepickerVar.start` and `yourDatepickerVar.end`. This should solve your issue.

**Comment by andreas-pa** [comment]
Thank you so much for your quick reply! 

It worked like a charm!
