### ISSUE TITLE
When I select a range between two years or next year the datepicker opens in the current month

### ISSUE THREAD

**Issue by Shinally** [benitolopez/hotel-datepicker#98]
Hi, 
![CalendarIssue](https://user-images.githubusercontent.com/40515824/112623621-db119580-8e2c-11eb-98ba-7723e43ee385.png)

I'm using the datepicker and if I select a range between 2021 or in 2022 the datepicker is opened in the current month (also my startDate is equal to new Date() but it lets me select dates from past) and not displays the range selected.
The input's format is 'ddd D MMM' but I have stored dates with years using 'start' and 'end', the datepicker reads badly. Maybe because I print the value in a format that it doesn't consider the year..

Thank you!

**Comment by benitolopez** [comment]
Hello,

This library is not meant to be used without specifying the year in the format. If you need to use it in that way, unfortunately, I'm not able to offer my help.
